// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/pyvcloudprovider.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/pyvcloudprovider.proto
	proto/vapp.proto
	proto/catalog_item.proto
	proto/disk.proto
	proto/org.proto
	proto/user.proto

It has these top-level messages:
	LoginCredentials
	LoginResult
	Catalog
	ReadCatalogResult
	CreateCatalogResult
	DeleteCatalogResult
	CheckResolvedResult
	StopResult
	StopInfo
	CreateVAppInfo
	CreateVAppResult
	DeleteVAppInfo
	DeleteVAppResult
	ReadVAppInfo
	ReadVAppResult
	CatalogUploadMediaInfo
	CatalogUploadMediaResult
	CatalogUploadOvaInfo
	CatalogCheckResolvedInfo
	CatalogUploadOvaResult
	DeleteCatalogItemInfo
	DeleteCatalogItemResult
	IsPresentCatalogItemInfo
	IsPresentCatalogItemResult
	CaptureVAppInfo
	CaptureVAppResult
	CreateDiskInfo
	CreateDiskResult
	DeleteDiskInfo
	DeleteDiskResult
	ReadDiskInfo
	ReadDiskResult
	CreateOrgInfo
	CreateOrgResult
	DeleteOrgInfo
	DeleteOrgResult
	ReadOrgInfo
	ReadOrgResult
	UpdateOrgInfo
	UpdateOrgResult
	CreateUserInfo
	CreateUserResult
	DeleteUserInfo
	DeleteUserResult
	ReadUserInfo
	ReadUserResult
	UpdateUserInfo
	UpdateUserResult
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Tenant VCD crendentials
type LoginCredentials struct {
	Username          string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password          string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Org               string `protobuf:"bytes,3,opt,name=org" json:"org,omitempty"`
	UseVcdCliProfile  bool   `protobuf:"varint,4,opt,name=use_vcd_cli_profile,json=useVcdCliProfile" json:"use_vcd_cli_profile,omitempty"`
	Ip                string `protobuf:"bytes,5,opt,name=ip" json:"ip,omitempty"`
	AllowInsecureFlag bool   `protobuf:"varint,6,opt,name=allow_insecure_flag,json=allowInsecureFlag" json:"allow_insecure_flag,omitempty"`
}

func (m *LoginCredentials) Reset()                    { *m = LoginCredentials{} }
func (m *LoginCredentials) String() string            { return proto1.CompactTextString(m) }
func (*LoginCredentials) ProtoMessage()               {}
func (*LoginCredentials) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginCredentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginCredentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginCredentials) GetOrg() string {
	if m != nil {
		return m.Org
	}
	return ""
}

func (m *LoginCredentials) GetUseVcdCliProfile() bool {
	if m != nil {
		return m.UseVcdCliProfile
	}
	return false
}

func (m *LoginCredentials) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *LoginCredentials) GetAllowInsecureFlag() bool {
	if m != nil {
		return m.AllowInsecureFlag
	}
	return false
}

type LoginResult struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *LoginResult) Reset()                    { *m = LoginResult{} }
func (m *LoginResult) String() string            { return proto1.CompactTextString(m) }
func (*LoginResult) ProtoMessage()               {}
func (*LoginResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginResult) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Catalog struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Shared      bool   `protobuf:"varint,3,opt,name=shared" json:"shared,omitempty"`
}

func (m *Catalog) Reset()                    { *m = Catalog{} }
func (m *Catalog) String() string            { return proto1.CompactTextString(m) }
func (*Catalog) ProtoMessage()               {}
func (*Catalog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Catalog) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Catalog) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Catalog) GetShared() bool {
	if m != nil {
		return m.Shared
	}
	return false
}

type ReadCatalogResult struct {
	Present     bool   `protobuf:"varint,1,opt,name=present" json:"present,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Shared      bool   `protobuf:"varint,4,opt,name=shared" json:"shared,omitempty"`
}

func (m *ReadCatalogResult) Reset()                    { *m = ReadCatalogResult{} }
func (m *ReadCatalogResult) String() string            { return proto1.CompactTextString(m) }
func (*ReadCatalogResult) ProtoMessage()               {}
func (*ReadCatalogResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadCatalogResult) GetPresent() bool {
	if m != nil {
		return m.Present
	}
	return false
}

func (m *ReadCatalogResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReadCatalogResult) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ReadCatalogResult) GetShared() bool {
	if m != nil {
		return m.Shared
	}
	return false
}

type CreateCatalogResult struct {
	Created bool `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
}

func (m *CreateCatalogResult) Reset()                    { *m = CreateCatalogResult{} }
func (m *CreateCatalogResult) String() string            { return proto1.CompactTextString(m) }
func (*CreateCatalogResult) ProtoMessage()               {}
func (*CreateCatalogResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateCatalogResult) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

type DeleteCatalogResult struct {
	Deleted bool `protobuf:"varint,1,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *DeleteCatalogResult) Reset()                    { *m = DeleteCatalogResult{} }
func (m *DeleteCatalogResult) String() string            { return proto1.CompactTextString(m) }
func (*DeleteCatalogResult) ProtoMessage()               {}
func (*DeleteCatalogResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteCatalogResult) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

// common
type CheckResolvedResult struct {
	Resolved bool `protobuf:"varint,1,opt,name=resolved" json:"resolved,omitempty"`
}

func (m *CheckResolvedResult) Reset()                    { *m = CheckResolvedResult{} }
func (m *CheckResolvedResult) String() string            { return proto1.CompactTextString(m) }
func (*CheckResolvedResult) ProtoMessage()               {}
func (*CheckResolvedResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CheckResolvedResult) GetResolved() bool {
	if m != nil {
		return m.Resolved
	}
	return false
}

type StopResult struct {
	Stopped bool `protobuf:"varint,1,opt,name=stopped" json:"stopped,omitempty"`
}

func (m *StopResult) Reset()                    { *m = StopResult{} }
func (m *StopResult) String() string            { return proto1.CompactTextString(m) }
func (*StopResult) ProtoMessage()               {}
func (*StopResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *StopResult) GetStopped() bool {
	if m != nil {
		return m.Stopped
	}
	return false
}

type StopInfo struct {
}

func (m *StopInfo) Reset()                    { *m = StopInfo{} }
func (m *StopInfo) String() string            { return proto1.CompactTextString(m) }
func (*StopInfo) ProtoMessage()               {}
func (*StopInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto1.RegisterType((*LoginCredentials)(nil), "proto.LoginCredentials")
	proto1.RegisterType((*LoginResult)(nil), "proto.LoginResult")
	proto1.RegisterType((*Catalog)(nil), "proto.Catalog")
	proto1.RegisterType((*ReadCatalogResult)(nil), "proto.ReadCatalogResult")
	proto1.RegisterType((*CreateCatalogResult)(nil), "proto.CreateCatalogResult")
	proto1.RegisterType((*DeleteCatalogResult)(nil), "proto.DeleteCatalogResult")
	proto1.RegisterType((*CheckResolvedResult)(nil), "proto.CheckResolvedResult")
	proto1.RegisterType((*StopResult)(nil), "proto.StopResult")
	proto1.RegisterType((*StopInfo)(nil), "proto.StopInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PyVcloudProvider service

type PyVcloudProviderClient interface {
	// Tenant Loging to VCD
	Login(ctx context.Context, in *LoginCredentials, opts ...grpc.CallOption) (*LoginResult, error)
	// check if catalog is preset and return true and the catalog details
	ReadCatalog(ctx context.Context, in *Catalog, opts ...grpc.CallOption) (*ReadCatalogResult, error)
	// create a new catalog
	CreateCatalog(ctx context.Context, in *Catalog, opts ...grpc.CallOption) (*CreateCatalogResult, error)
	// delete a catalog
	DeleteCatalog(ctx context.Context, in *Catalog, opts ...grpc.CallOption) (*DeleteCatalogResult, error)
	// catalog upload Media - anything other than ova
	CatalogUploadMedia(ctx context.Context, in *CatalogUploadMediaInfo, opts ...grpc.CallOption) (*CatalogUploadMediaResult, error)
	// catalog upload ova
	CatalogUploadOva(ctx context.Context, in *CatalogUploadOvaInfo, opts ...grpc.CallOption) (*CatalogUploadOvaResult, error)
	// check resolved after upload
	OvaCheckResolved(ctx context.Context, in *CatalogCheckResolvedInfo, opts ...grpc.CallOption) (*CheckResolvedResult, error)
	// catalog item delete
	DeleteCatalogItem(ctx context.Context, in *DeleteCatalogItemInfo, opts ...grpc.CallOption) (*DeleteCatalogItemResult, error)
	// check if catalog item is preset and return true
	IsPresentCatalogItem(ctx context.Context, in *IsPresentCatalogItemInfo, opts ...grpc.CallOption) (*IsPresentCatalogItemResult, error)
	CaptureVapp(ctx context.Context, in *CaptureVAppInfo, opts ...grpc.CallOption) (*CaptureVAppResult, error)
	// create vApp
	CreateVApp(ctx context.Context, in *CreateVAppInfo, opts ...grpc.CallOption) (*CreateVAppResult, error)
	// delete VApp
	DeleteVApp(ctx context.Context, in *DeleteVAppInfo, opts ...grpc.CallOption) (*DeleteVAppResult, error)
	// Read VApp
	ReadVApp(ctx context.Context, in *ReadVAppInfo, opts ...grpc.CallOption) (*ReadVAppResult, error)
	// remote stop interface for the plugin
	StopPlugin(ctx context.Context, in *StopInfo, opts ...grpc.CallOption) (*StopResult, error)
}

type pyVcloudProviderClient struct {
	cc *grpc.ClientConn
}

func NewPyVcloudProviderClient(cc *grpc.ClientConn) PyVcloudProviderClient {
	return &pyVcloudProviderClient{cc}
}

func (c *pyVcloudProviderClient) Login(ctx context.Context, in *LoginCredentials, opts ...grpc.CallOption) (*LoginResult, error) {
	out := new(LoginResult)
	err := grpc.Invoke(ctx, "/proto.PyVcloudProvider/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pyVcloudProviderClient) ReadCatalog(ctx context.Context, in *Catalog, opts ...grpc.CallOption) (*ReadCatalogResult, error) {
	out := new(ReadCatalogResult)
	err := grpc.Invoke(ctx, "/proto.PyVcloudProvider/ReadCatalog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pyVcloudProviderClient) CreateCatalog(ctx context.Context, in *Catalog, opts ...grpc.CallOption) (*CreateCatalogResult, error) {
	out := new(CreateCatalogResult)
	err := grpc.Invoke(ctx, "/proto.PyVcloudProvider/CreateCatalog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pyVcloudProviderClient) DeleteCatalog(ctx context.Context, in *Catalog, opts ...grpc.CallOption) (*DeleteCatalogResult, error) {
	out := new(DeleteCatalogResult)
	err := grpc.Invoke(ctx, "/proto.PyVcloudProvider/DeleteCatalog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pyVcloudProviderClient) CatalogUploadMedia(ctx context.Context, in *CatalogUploadMediaInfo, opts ...grpc.CallOption) (*CatalogUploadMediaResult, error) {
	out := new(CatalogUploadMediaResult)
	err := grpc.Invoke(ctx, "/proto.PyVcloudProvider/CatalogUploadMedia", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pyVcloudProviderClient) CatalogUploadOva(ctx context.Context, in *CatalogUploadOvaInfo, opts ...grpc.CallOption) (*CatalogUploadOvaResult, error) {
	out := new(CatalogUploadOvaResult)
	err := grpc.Invoke(ctx, "/proto.PyVcloudProvider/CatalogUploadOva", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pyVcloudProviderClient) OvaCheckResolved(ctx context.Context, in *CatalogCheckResolvedInfo, opts ...grpc.CallOption) (*CheckResolvedResult, error) {
	out := new(CheckResolvedResult)
	err := grpc.Invoke(ctx, "/proto.PyVcloudProvider/OvaCheckResolved", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pyVcloudProviderClient) DeleteCatalogItem(ctx context.Context, in *DeleteCatalogItemInfo, opts ...grpc.CallOption) (*DeleteCatalogItemResult, error) {
	out := new(DeleteCatalogItemResult)
	err := grpc.Invoke(ctx, "/proto.PyVcloudProvider/DeleteCatalogItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pyVcloudProviderClient) IsPresentCatalogItem(ctx context.Context, in *IsPresentCatalogItemInfo, opts ...grpc.CallOption) (*IsPresentCatalogItemResult, error) {
	out := new(IsPresentCatalogItemResult)
	err := grpc.Invoke(ctx, "/proto.PyVcloudProvider/isPresentCatalogItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pyVcloudProviderClient) CaptureVapp(ctx context.Context, in *CaptureVAppInfo, opts ...grpc.CallOption) (*CaptureVAppResult, error) {
	out := new(CaptureVAppResult)
	err := grpc.Invoke(ctx, "/proto.PyVcloudProvider/CaptureVapp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pyVcloudProviderClient) CreateVApp(ctx context.Context, in *CreateVAppInfo, opts ...grpc.CallOption) (*CreateVAppResult, error) {
	out := new(CreateVAppResult)
	err := grpc.Invoke(ctx, "/proto.PyVcloudProvider/CreateVApp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pyVcloudProviderClient) DeleteVApp(ctx context.Context, in *DeleteVAppInfo, opts ...grpc.CallOption) (*DeleteVAppResult, error) {
	out := new(DeleteVAppResult)
	err := grpc.Invoke(ctx, "/proto.PyVcloudProvider/DeleteVApp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pyVcloudProviderClient) ReadVApp(ctx context.Context, in *ReadVAppInfo, opts ...grpc.CallOption) (*ReadVAppResult, error) {
	out := new(ReadVAppResult)
	err := grpc.Invoke(ctx, "/proto.PyVcloudProvider/ReadVApp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pyVcloudProviderClient) StopPlugin(ctx context.Context, in *StopInfo, opts ...grpc.CallOption) (*StopResult, error) {
	out := new(StopResult)
	err := grpc.Invoke(ctx, "/proto.PyVcloudProvider/StopPlugin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PyVcloudProvider service

type PyVcloudProviderServer interface {
	// Tenant Loging to VCD
	Login(context.Context, *LoginCredentials) (*LoginResult, error)
	// check if catalog is preset and return true and the catalog details
	ReadCatalog(context.Context, *Catalog) (*ReadCatalogResult, error)
	// create a new catalog
	CreateCatalog(context.Context, *Catalog) (*CreateCatalogResult, error)
	// delete a catalog
	DeleteCatalog(context.Context, *Catalog) (*DeleteCatalogResult, error)
	// catalog upload Media - anything other than ova
	CatalogUploadMedia(context.Context, *CatalogUploadMediaInfo) (*CatalogUploadMediaResult, error)
	// catalog upload ova
	CatalogUploadOva(context.Context, *CatalogUploadOvaInfo) (*CatalogUploadOvaResult, error)
	// check resolved after upload
	OvaCheckResolved(context.Context, *CatalogCheckResolvedInfo) (*CheckResolvedResult, error)
	// catalog item delete
	DeleteCatalogItem(context.Context, *DeleteCatalogItemInfo) (*DeleteCatalogItemResult, error)
	// check if catalog item is preset and return true
	IsPresentCatalogItem(context.Context, *IsPresentCatalogItemInfo) (*IsPresentCatalogItemResult, error)
	CaptureVapp(context.Context, *CaptureVAppInfo) (*CaptureVAppResult, error)
	// create vApp
	CreateVApp(context.Context, *CreateVAppInfo) (*CreateVAppResult, error)
	// delete VApp
	DeleteVApp(context.Context, *DeleteVAppInfo) (*DeleteVAppResult, error)
	// Read VApp
	ReadVApp(context.Context, *ReadVAppInfo) (*ReadVAppResult, error)
	// remote stop interface for the plugin
	StopPlugin(context.Context, *StopInfo) (*StopResult, error)
}

func RegisterPyVcloudProviderServer(s *grpc.Server, srv PyVcloudProviderServer) {
	s.RegisterService(&_PyVcloudProvider_serviceDesc, srv)
}

func _PyVcloudProvider_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginCredentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PyVcloudProviderServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PyVcloudProvider/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PyVcloudProviderServer).Login(ctx, req.(*LoginCredentials))
	}
	return interceptor(ctx, in, info, handler)
}

func _PyVcloudProvider_ReadCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Catalog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PyVcloudProviderServer).ReadCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PyVcloudProvider/ReadCatalog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PyVcloudProviderServer).ReadCatalog(ctx, req.(*Catalog))
	}
	return interceptor(ctx, in, info, handler)
}

func _PyVcloudProvider_CreateCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Catalog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PyVcloudProviderServer).CreateCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PyVcloudProvider/CreateCatalog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PyVcloudProviderServer).CreateCatalog(ctx, req.(*Catalog))
	}
	return interceptor(ctx, in, info, handler)
}

func _PyVcloudProvider_DeleteCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Catalog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PyVcloudProviderServer).DeleteCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PyVcloudProvider/DeleteCatalog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PyVcloudProviderServer).DeleteCatalog(ctx, req.(*Catalog))
	}
	return interceptor(ctx, in, info, handler)
}

func _PyVcloudProvider_CatalogUploadMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CatalogUploadMediaInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PyVcloudProviderServer).CatalogUploadMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PyVcloudProvider/CatalogUploadMedia",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PyVcloudProviderServer).CatalogUploadMedia(ctx, req.(*CatalogUploadMediaInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _PyVcloudProvider_CatalogUploadOva_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CatalogUploadOvaInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PyVcloudProviderServer).CatalogUploadOva(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PyVcloudProvider/CatalogUploadOva",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PyVcloudProviderServer).CatalogUploadOva(ctx, req.(*CatalogUploadOvaInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _PyVcloudProvider_OvaCheckResolved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CatalogCheckResolvedInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PyVcloudProviderServer).OvaCheckResolved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PyVcloudProvider/OvaCheckResolved",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PyVcloudProviderServer).OvaCheckResolved(ctx, req.(*CatalogCheckResolvedInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _PyVcloudProvider_DeleteCatalogItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCatalogItemInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PyVcloudProviderServer).DeleteCatalogItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PyVcloudProvider/DeleteCatalogItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PyVcloudProviderServer).DeleteCatalogItem(ctx, req.(*DeleteCatalogItemInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _PyVcloudProvider_IsPresentCatalogItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsPresentCatalogItemInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PyVcloudProviderServer).IsPresentCatalogItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PyVcloudProvider/IsPresentCatalogItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PyVcloudProviderServer).IsPresentCatalogItem(ctx, req.(*IsPresentCatalogItemInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _PyVcloudProvider_CaptureVapp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureVAppInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PyVcloudProviderServer).CaptureVapp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PyVcloudProvider/CaptureVapp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PyVcloudProviderServer).CaptureVapp(ctx, req.(*CaptureVAppInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _PyVcloudProvider_CreateVApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVAppInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PyVcloudProviderServer).CreateVApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PyVcloudProvider/CreateVApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PyVcloudProviderServer).CreateVApp(ctx, req.(*CreateVAppInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _PyVcloudProvider_DeleteVApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVAppInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PyVcloudProviderServer).DeleteVApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PyVcloudProvider/DeleteVApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PyVcloudProviderServer).DeleteVApp(ctx, req.(*DeleteVAppInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _PyVcloudProvider_ReadVApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadVAppInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PyVcloudProviderServer).ReadVApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PyVcloudProvider/ReadVApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PyVcloudProviderServer).ReadVApp(ctx, req.(*ReadVAppInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _PyVcloudProvider_StopPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PyVcloudProviderServer).StopPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PyVcloudProvider/StopPlugin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PyVcloudProviderServer).StopPlugin(ctx, req.(*StopInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _PyVcloudProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PyVcloudProvider",
	HandlerType: (*PyVcloudProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _PyVcloudProvider_Login_Handler,
		},
		{
			MethodName: "ReadCatalog",
			Handler:    _PyVcloudProvider_ReadCatalog_Handler,
		},
		{
			MethodName: "CreateCatalog",
			Handler:    _PyVcloudProvider_CreateCatalog_Handler,
		},
		{
			MethodName: "DeleteCatalog",
			Handler:    _PyVcloudProvider_DeleteCatalog_Handler,
		},
		{
			MethodName: "CatalogUploadMedia",
			Handler:    _PyVcloudProvider_CatalogUploadMedia_Handler,
		},
		{
			MethodName: "CatalogUploadOva",
			Handler:    _PyVcloudProvider_CatalogUploadOva_Handler,
		},
		{
			MethodName: "OvaCheckResolved",
			Handler:    _PyVcloudProvider_OvaCheckResolved_Handler,
		},
		{
			MethodName: "DeleteCatalogItem",
			Handler:    _PyVcloudProvider_DeleteCatalogItem_Handler,
		},
		{
			MethodName: "isPresentCatalogItem",
			Handler:    _PyVcloudProvider_IsPresentCatalogItem_Handler,
		},
		{
			MethodName: "CaptureVapp",
			Handler:    _PyVcloudProvider_CaptureVapp_Handler,
		},
		{
			MethodName: "CreateVApp",
			Handler:    _PyVcloudProvider_CreateVApp_Handler,
		},
		{
			MethodName: "DeleteVApp",
			Handler:    _PyVcloudProvider_DeleteVApp_Handler,
		},
		{
			MethodName: "ReadVApp",
			Handler:    _PyVcloudProvider_ReadVApp_Handler,
		},
		{
			MethodName: "StopPlugin",
			Handler:    _PyVcloudProvider_StopPlugin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pyvcloudprovider.proto",
}

func init() { proto1.RegisterFile("proto/pyvcloudprovider.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 713 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0x6d, 0x6f, 0xd3, 0x3c,
	0x14, 0x6d, 0xbb, 0x75, 0xeb, 0x73, 0xab, 0x67, 0xb4, 0xee, 0x5e, 0xa2, 0xb0, 0xc1, 0x08, 0x12,
	0xda, 0x17, 0x3a, 0x31, 0x24, 0x5e, 0x3e, 0x80, 0xb4, 0x15, 0x21, 0x55, 0x02, 0x2d, 0x74, 0xa2,
	0x7c, 0x41, 0xaa, 0x4c, 0x72, 0xd7, 0x45, 0x4b, 0x63, 0xcb, 0x79, 0x99, 0x26, 0x7e, 0x22, 0x7f,
	0x83, 0x1f, 0x82, 0x62, 0x3b, 0x6e, 0xd2, 0x97, 0x7d, 0x6a, 0xce, 0x39, 0x3e, 0xe7, 0xc6, 0xd7,
	0xd7, 0x0d, 0x1c, 0x72, 0xc1, 0x12, 0x76, 0xca, 0xef, 0x33, 0x2f, 0x64, 0xa9, 0xcf, 0x05, 0xcb,
	0x02, 0x1f, 0x45, 0x5f, 0xd2, 0xa4, 0x29, 0x7f, 0xec, 0x8e, 0x5a, 0x94, 0x51, 0xce, 0x95, 0x60,
	0x5b, 0x8a, 0xf1, 0x68, 0x42, 0x43, 0x36, 0x9d, 0x04, 0x09, 0xce, 0x94, 0xe2, 0xfc, 0xa9, 0x43,
	0xe7, 0x0b, 0x9b, 0x06, 0xd1, 0x40, 0xa0, 0x8f, 0x51, 0x12, 0xd0, 0x30, 0x26, 0x36, 0xb4, 0xd2,
	0x18, 0x45, 0x44, 0x67, 0x68, 0xd5, 0x8f, 0xeb, 0x27, 0xff, 0x8d, 0x0c, 0xce, 0x35, 0x4e, 0xe3,
	0xf8, 0x8e, 0x09, 0xdf, 0x6a, 0x28, 0xad, 0xc0, 0xa4, 0x03, 0x1b, 0x4c, 0x4c, 0xad, 0x0d, 0x49,
	0xe7, 0x8f, 0xe4, 0x25, 0xf4, 0xd2, 0x18, 0x27, 0x99, 0xe7, 0x4f, 0xbc, 0x30, 0x98, 0x70, 0xc1,
	0xae, 0x83, 0x10, 0xad, 0xcd, 0xe3, 0xfa, 0x49, 0x6b, 0xd4, 0x49, 0x63, 0x1c, 0x7b, 0xfe, 0x20,
	0x0c, 0x5c, 0xc5, 0x93, 0x1d, 0x68, 0x04, 0xdc, 0x6a, 0x4a, 0x7f, 0x23, 0xe0, 0xa4, 0x0f, 0x3d,
	0x1a, 0x86, 0xec, 0x6e, 0x12, 0x44, 0x31, 0x7a, 0xa9, 0xc0, 0xc9, 0x75, 0x48, 0xa7, 0xd6, 0x96,
	0xb4, 0x77, 0xa5, 0x34, 0xd4, 0xca, 0xe7, 0x90, 0x4e, 0x9d, 0xe7, 0xd0, 0x96, 0x9b, 0x19, 0x61,
	0x9c, 0x86, 0x09, 0xd9, 0x85, 0x66, 0xc2, 0x6e, 0x31, 0xd2, 0x9b, 0x50, 0xc0, 0xf9, 0x01, 0xdb,
	0x03, 0xd5, 0x08, 0x42, 0x60, 0xb3, 0xb4, 0x49, 0xf9, 0x4c, 0x8e, 0xa1, 0xed, 0x63, 0xec, 0x89,
	0x80, 0x27, 0x01, 0x8b, 0xf4, 0x1e, 0xcb, 0x14, 0xd9, 0x87, 0xad, 0xf8, 0x86, 0x0a, 0xf4, 0xe5,
	0x4e, 0x5b, 0x23, 0x8d, 0x9c, 0xdf, 0xd0, 0x1d, 0x21, 0xf5, 0x75, 0xb8, 0x7e, 0x07, 0x0b, 0xb6,
	0xb9, 0xc0, 0x18, 0xa3, 0x44, 0x56, 0x69, 0x8d, 0x0a, 0x68, 0x8a, 0x37, 0xd6, 0x17, 0xdf, 0x78,
	0xa8, 0xf8, 0x66, 0xa5, 0xf8, 0x29, 0xf4, 0x06, 0x02, 0x69, 0x82, 0x4b, 0xe5, 0x3d, 0x49, 0xfb,
	0x45, 0x79, 0x0d, 0x73, 0xc3, 0x27, 0x0c, 0x71, 0x85, 0xc1, 0x97, 0xb4, 0x31, 0x68, 0xe8, 0xbc,
	0x82, 0xde, 0xe0, 0x06, 0xbd, 0xdb, 0x11, 0xc6, 0x2c, 0xcc, 0xd0, 0xd7, 0x06, 0x1b, 0x5a, 0x42,
	0x33, 0xda, 0x61, 0xb0, 0xf3, 0x02, 0xe0, 0x2a, 0x61, 0x7c, 0x1e, 0x1d, 0x27, 0x8c, 0xf3, 0x79,
	0xb4, 0x86, 0x0e, 0x40, 0x2b, 0x5f, 0x37, 0x8c, 0xae, 0xd9, 0xd9, 0xdf, 0x6d, 0xe8, 0xb8, 0xf7,
	0x63, 0x39, 0xdf, 0xae, 0x9e, 0x6f, 0xf2, 0x06, 0x9a, 0xf2, 0x60, 0xc9, 0x81, 0x9a, 0xdb, 0xfe,
	0xe2, 0xcc, 0xda, 0xa4, 0x2c, 0xa8, 0x82, 0x4e, 0x8d, 0xbc, 0x87, 0x76, 0xe9, 0x48, 0xc8, 0x8e,
	0x5e, 0xa4, 0xb1, 0x6d, 0x69, 0xbc, 0x74, 0x6c, 0x4e, 0x8d, 0x7c, 0x80, 0xff, 0x2b, 0x0d, 0x5d,
	0x32, 0xdb, 0x05, 0x5e, 0x6e, 0xbb, 0xb2, 0x57, 0xda, 0xbb, 0xd6, 0xbe, 0xe2, 0x10, 0x9c, 0x1a,
	0x19, 0x03, 0xd1, 0xd4, 0x77, 0x1e, 0x32, 0xea, 0x7f, 0x45, 0x3f, 0xa0, 0xe4, 0xa8, 0x9a, 0x51,
	0x92, 0xf2, 0xd6, 0xd9, 0x4f, 0xd7, 0xca, 0x26, 0xd7, 0x85, 0x4e, 0x45, 0xbd, 0xcc, 0x28, 0x79,
	0xbc, 0xca, 0x76, 0x99, 0xa9, 0xcc, 0xa3, 0x35, 0xa2, 0x49, 0xfc, 0x06, 0x9d, 0xcb, 0x8c, 0x56,
	0x26, 0x83, 0x2c, 0xbc, 0x48, 0x45, 0x94, 0xa9, 0xa6, 0x77, 0xcb, 0x03, 0xe5, 0xd4, 0xc8, 0x15,
	0x74, 0x2b, 0x5d, 0x19, 0x26, 0x38, 0x23, 0x87, 0xab, 0xfa, 0x95, 0x2b, 0x32, 0xf0, 0xc9, 0x3a,
	0xd5, 0x84, 0xfe, 0x84, 0xdd, 0x20, 0x76, 0xd5, 0xdd, 0x2b, 0xe7, 0x16, 0xef, 0x3a, 0x5c, 0x21,
	0xca, 0xe8, 0x67, 0x0f, 0x2c, 0x30, 0xe9, 0xe7, 0xd0, 0x1e, 0x50, 0x9e, 0xa4, 0x02, 0xc7, 0x94,
	0x73, 0xb2, 0x6f, 0x1a, 0xa0, 0xb8, 0x73, 0x2e, 0x87, 0xdb, 0x0c, 0x5c, 0x89, 0x37, 0x11, 0x1f,
	0x01, 0xd4, 0x28, 0xe5, 0x2c, 0xd9, 0xab, 0x4c, 0x97, 0x09, 0x38, 0x58, 0xa2, 0xcb, 0x7e, 0xb5,
	0xfb, 0x8a, 0x7f, 0x4e, 0x55, 0xfc, 0x73, 0xda, 0xf8, 0xdf, 0x41, 0x2b, 0xbf, 0x07, 0xd2, 0xdd,
	0x2b, 0x5d, 0x0c, 0xe3, 0xdd, 0x5b, 0x20, 0x8d, 0xf3, 0x4c, 0x5d, 0x73, 0x37, 0x4c, 0xf3, 0x2b,
	0xfa, 0x48, 0x2f, 0x2b, 0x6e, 0xb4, 0xdd, 0x2d, 0x11, 0x85, 0xe7, 0xe2, 0x2d, 0x1c, 0x7a, 0x6c,
	0xd6, 0xcf, 0x66, 0x77, 0x54, 0x60, 0xbf, 0xf8, 0xa0, 0xf5, 0x8b, 0x2f, 0xda, 0xc5, 0xde, 0xe2,
	0x7f, 0x80, 0x9b, 0x67, 0xb8, 0xf5, 0x5f, 0x5b, 0x32, 0xec, 0xf5, 0xbf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xeb, 0xbd, 0xd3, 0xeb, 0x0b, 0x07, 0x00, 0x00,
}
