// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateUserInfo struct {
	Name             string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password         string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	RoleName         string `protobuf:"bytes,3,opt,name=role_name,json=roleName" json:"role_name,omitempty"`
	FullName         string `protobuf:"bytes,4,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	Description      string `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Email            string `protobuf:"bytes,6,opt,name=email" json:"email,omitempty"`
	Telephone        string `protobuf:"bytes,7,opt,name=telephone" json:"telephone,omitempty"`
	Im               string `protobuf:"bytes,8,opt,name=im" json:"im,omitempty"`
	AlertEmail       string `protobuf:"bytes,9,opt,name=alert_email,json=alertEmail" json:"alert_email,omitempty"`
	AlertEmailPrefix string `protobuf:"bytes,10,opt,name=alert_email_prefix,json=alertEmailPrefix" json:"alert_email_prefix,omitempty"`
	StoredVmQuota    int32  `protobuf:"varint,11,opt,name=stored_vm_quota,json=storedVmQuota" json:"stored_vm_quota,omitempty"`
	DeployedVmQuota  int32  `protobuf:"varint,12,opt,name=deployed_vm_quota,json=deployedVmQuota" json:"deployed_vm_quota,omitempty"`
	IsGroupRole      bool   `protobuf:"varint,13,opt,name=is_group_role,json=isGroupRole" json:"is_group_role,omitempty"`
	IsDefaultCached  bool   `protobuf:"varint,14,opt,name=is_default_cached,json=isDefaultCached" json:"is_default_cached,omitempty"`
	IsExternal       bool   `protobuf:"varint,15,opt,name=is_external,json=isExternal" json:"is_external,omitempty"`
	IsAlertEnabled   bool   `protobuf:"varint,16,opt,name=is_alert_enabled,json=isAlertEnabled" json:"is_alert_enabled,omitempty"`
	IsEnabled        bool   `protobuf:"varint,17,opt,name=is_enabled,json=isEnabled" json:"is_enabled,omitempty"`
}

func (m *CreateUserInfo) Reset()                    { *m = CreateUserInfo{} }
func (m *CreateUserInfo) String() string            { return proto1.CompactTextString(m) }
func (*CreateUserInfo) ProtoMessage()               {}
func (*CreateUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *CreateUserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserInfo) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *CreateUserInfo) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *CreateUserInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateUserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserInfo) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *CreateUserInfo) GetIm() string {
	if m != nil {
		return m.Im
	}
	return ""
}

func (m *CreateUserInfo) GetAlertEmail() string {
	if m != nil {
		return m.AlertEmail
	}
	return ""
}

func (m *CreateUserInfo) GetAlertEmailPrefix() string {
	if m != nil {
		return m.AlertEmailPrefix
	}
	return ""
}

func (m *CreateUserInfo) GetStoredVmQuota() int32 {
	if m != nil {
		return m.StoredVmQuota
	}
	return 0
}

func (m *CreateUserInfo) GetDeployedVmQuota() int32 {
	if m != nil {
		return m.DeployedVmQuota
	}
	return 0
}

func (m *CreateUserInfo) GetIsGroupRole() bool {
	if m != nil {
		return m.IsGroupRole
	}
	return false
}

func (m *CreateUserInfo) GetIsDefaultCached() bool {
	if m != nil {
		return m.IsDefaultCached
	}
	return false
}

func (m *CreateUserInfo) GetIsExternal() bool {
	if m != nil {
		return m.IsExternal
	}
	return false
}

func (m *CreateUserInfo) GetIsAlertEnabled() bool {
	if m != nil {
		return m.IsAlertEnabled
	}
	return false
}

func (m *CreateUserInfo) GetIsEnabled() bool {
	if m != nil {
		return m.IsEnabled
	}
	return false
}

type CreateUserResult struct {
	Created bool `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
}

func (m *CreateUserResult) Reset()                    { *m = CreateUserResult{} }
func (m *CreateUserResult) String() string            { return proto1.CompactTextString(m) }
func (*CreateUserResult) ProtoMessage()               {}
func (*CreateUserResult) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *CreateUserResult) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

type DeleteUserInfo struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DeleteUserInfo) Reset()                    { *m = DeleteUserInfo{} }
func (m *DeleteUserInfo) String() string            { return proto1.CompactTextString(m) }
func (*DeleteUserInfo) ProtoMessage()               {}
func (*DeleteUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *DeleteUserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteUserResult struct {
	Deleted bool `protobuf:"varint,1,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *DeleteUserResult) Reset()                    { *m = DeleteUserResult{} }
func (m *DeleteUserResult) String() string            { return proto1.CompactTextString(m) }
func (*DeleteUserResult) ProtoMessage()               {}
func (*DeleteUserResult) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *DeleteUserResult) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type ReadUserInfo struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ReadUserInfo) Reset()                    { *m = ReadUserInfo{} }
func (m *ReadUserInfo) String() string            { return proto1.CompactTextString(m) }
func (*ReadUserInfo) ProtoMessage()               {}
func (*ReadUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *ReadUserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReadUserResult struct {
	Name             string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	RoleName         string `protobuf:"bytes,2,opt,name=role_name,json=roleName" json:"role_name,omitempty"`
	FullName         string `protobuf:"bytes,3,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	Description      string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Email            string `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	Telephone        string `protobuf:"bytes,6,opt,name=telephone" json:"telephone,omitempty"`
	Im               string `protobuf:"bytes,7,opt,name=im" json:"im,omitempty"`
	AlertEmail       string `protobuf:"bytes,8,opt,name=alert_email,json=alertEmail" json:"alert_email,omitempty"`
	AlertEmailPrefix string `protobuf:"bytes,9,opt,name=alert_email_prefix,json=alertEmailPrefix" json:"alert_email_prefix,omitempty"`
	StoredVmQuota    int32  `protobuf:"varint,10,opt,name=stored_vm_quota,json=storedVmQuota" json:"stored_vm_quota,omitempty"`
	DeployedVmQuota  int32  `protobuf:"varint,11,opt,name=deployed_vm_quota,json=deployedVmQuota" json:"deployed_vm_quota,omitempty"`
	IsGroupRole      bool   `protobuf:"varint,12,opt,name=is_group_role,json=isGroupRole" json:"is_group_role,omitempty"`
	IsDefaultCached  bool   `protobuf:"varint,13,opt,name=is_default_cached,json=isDefaultCached" json:"is_default_cached,omitempty"`
	IsExternal       bool   `protobuf:"varint,14,opt,name=is_external,json=isExternal" json:"is_external,omitempty"`
	IsAlertEnabled   bool   `protobuf:"varint,15,opt,name=is_alert_enabled,json=isAlertEnabled" json:"is_alert_enabled,omitempty"`
	IsEnabled        bool   `protobuf:"varint,16,opt,name=is_enabled,json=isEnabled" json:"is_enabled,omitempty"`
	Present          bool   `protobuf:"varint,17,opt,name=present" json:"present,omitempty"`
}

func (m *ReadUserResult) Reset()                    { *m = ReadUserResult{} }
func (m *ReadUserResult) String() string            { return proto1.CompactTextString(m) }
func (*ReadUserResult) ProtoMessage()               {}
func (*ReadUserResult) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *ReadUserResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReadUserResult) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *ReadUserResult) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *ReadUserResult) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ReadUserResult) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ReadUserResult) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *ReadUserResult) GetIm() string {
	if m != nil {
		return m.Im
	}
	return ""
}

func (m *ReadUserResult) GetAlertEmail() string {
	if m != nil {
		return m.AlertEmail
	}
	return ""
}

func (m *ReadUserResult) GetAlertEmailPrefix() string {
	if m != nil {
		return m.AlertEmailPrefix
	}
	return ""
}

func (m *ReadUserResult) GetStoredVmQuota() int32 {
	if m != nil {
		return m.StoredVmQuota
	}
	return 0
}

func (m *ReadUserResult) GetDeployedVmQuota() int32 {
	if m != nil {
		return m.DeployedVmQuota
	}
	return 0
}

func (m *ReadUserResult) GetIsGroupRole() bool {
	if m != nil {
		return m.IsGroupRole
	}
	return false
}

func (m *ReadUserResult) GetIsDefaultCached() bool {
	if m != nil {
		return m.IsDefaultCached
	}
	return false
}

func (m *ReadUserResult) GetIsExternal() bool {
	if m != nil {
		return m.IsExternal
	}
	return false
}

func (m *ReadUserResult) GetIsAlertEnabled() bool {
	if m != nil {
		return m.IsAlertEnabled
	}
	return false
}

func (m *ReadUserResult) GetIsEnabled() bool {
	if m != nil {
		return m.IsEnabled
	}
	return false
}

func (m *ReadUserResult) GetPresent() bool {
	if m != nil {
		return m.Present
	}
	return false
}

type UpdateUserInfo struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	IsEnabled bool   `protobuf:"varint,2,opt,name=is_enabled,json=isEnabled" json:"is_enabled,omitempty"`
}

func (m *UpdateUserInfo) Reset()                    { *m = UpdateUserInfo{} }
func (m *UpdateUserInfo) String() string            { return proto1.CompactTextString(m) }
func (*UpdateUserInfo) ProtoMessage()               {}
func (*UpdateUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

func (m *UpdateUserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserInfo) GetIsEnabled() bool {
	if m != nil {
		return m.IsEnabled
	}
	return false
}

type UpdateUserResult struct {
	Updated bool `protobuf:"varint,1,opt,name=updated" json:"updated,omitempty"`
}

func (m *UpdateUserResult) Reset()                    { *m = UpdateUserResult{} }
func (m *UpdateUserResult) String() string            { return proto1.CompactTextString(m) }
func (*UpdateUserResult) ProtoMessage()               {}
func (*UpdateUserResult) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

func (m *UpdateUserResult) GetUpdated() bool {
	if m != nil {
		return m.Updated
	}
	return false
}

func init() {
	proto1.RegisterType((*CreateUserInfo)(nil), "proto.CreateUserInfo")
	proto1.RegisterType((*CreateUserResult)(nil), "proto.CreateUserResult")
	proto1.RegisterType((*DeleteUserInfo)(nil), "proto.DeleteUserInfo")
	proto1.RegisterType((*DeleteUserResult)(nil), "proto.DeleteUserResult")
	proto1.RegisterType((*ReadUserInfo)(nil), "proto.ReadUserInfo")
	proto1.RegisterType((*ReadUserResult)(nil), "proto.ReadUserResult")
	proto1.RegisterType((*UpdateUserInfo)(nil), "proto.UpdateUserInfo")
	proto1.RegisterType((*UpdateUserResult)(nil), "proto.UpdateUserResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for User service

type UserClient interface {
	// create a User
	Create(ctx context.Context, in *CreateUserInfo, opts ...grpc.CallOption) (*CreateUserResult, error)
	// delete a User
	Delete(ctx context.Context, in *DeleteUserInfo, opts ...grpc.CallOption) (*DeleteUserResult, error)
	// Read User
	Read(ctx context.Context, in *ReadUserInfo, opts ...grpc.CallOption) (*ReadUserResult, error)
	// Update User
	Update(ctx context.Context, in *UpdateUserInfo, opts ...grpc.CallOption) (*UpdateUserResult, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) Create(ctx context.Context, in *CreateUserInfo, opts ...grpc.CallOption) (*CreateUserResult, error) {
	out := new(CreateUserResult)
	err := grpc.Invoke(ctx, "/proto.User/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Delete(ctx context.Context, in *DeleteUserInfo, opts ...grpc.CallOption) (*DeleteUserResult, error) {
	out := new(DeleteUserResult)
	err := grpc.Invoke(ctx, "/proto.User/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Read(ctx context.Context, in *ReadUserInfo, opts ...grpc.CallOption) (*ReadUserResult, error) {
	out := new(ReadUserResult)
	err := grpc.Invoke(ctx, "/proto.User/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Update(ctx context.Context, in *UpdateUserInfo, opts ...grpc.CallOption) (*UpdateUserResult, error) {
	out := new(UpdateUserResult)
	err := grpc.Invoke(ctx, "/proto.User/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserServer interface {
	// create a User
	Create(context.Context, *CreateUserInfo) (*CreateUserResult, error)
	// delete a User
	Delete(context.Context, *DeleteUserInfo) (*DeleteUserResult, error)
	// Read User
	Read(context.Context, *ReadUserInfo) (*ReadUserResult, error)
	// Update User
	Update(context.Context, *UpdateUserInfo) (*UpdateUserResult, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.User/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Create(ctx, req.(*CreateUserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.User/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Delete(ctx, req.(*DeleteUserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadUserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.User/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Read(ctx, req.(*ReadUserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.User/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Update(ctx, req.(*UpdateUserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _User_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _User_Delete_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _User_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _User_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user.proto",
}

func init() { proto1.RegisterFile("proto/user.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0xd7, 0x2e, 0xed, 0x9a, 0xd3, 0x35, 0xed, 0x0c, 0x13, 0xd6, 0x06, 0xa2, 0x8a, 0x10,
	0xaa, 0xd0, 0x34, 0x24, 0xe0, 0x8a, 0x3b, 0xb4, 0x4d, 0x88, 0x1b, 0x04, 0x91, 0xc6, 0x6d, 0x94,
	0x35, 0xa7, 0xcc, 0x92, 0xf3, 0x07, 0x3b, 0x81, 0xf1, 0x6c, 0x88, 0x77, 0xe2, 0x11, 0x90, 0x8f,
	0xd3, 0xa4, 0x2d, 0x5d, 0xc9, 0x55, 0x72, 0xbe, 0xf3, 0xf9, 0xb3, 0x6c, 0xfd, 0x8e, 0x61, 0x92,
	0xab, 0xac, 0xc8, 0x5e, 0x96, 0x1a, 0xd5, 0x39, 0xfd, 0xb2, 0x1e, 0x7d, 0xfc, 0xdf, 0x0e, 0x78,
	0x17, 0x0a, 0xa3, 0x02, 0xaf, 0x35, 0xaa, 0x0f, 0xe9, 0x22, 0x63, 0x0c, 0x9c, 0x34, 0x4a, 0x90,
	0x77, 0xa6, 0x9d, 0x99, 0x1b, 0xd0, 0x3f, 0x3b, 0x81, 0x41, 0x1e, 0x69, 0xfd, 0x23, 0x53, 0x31,
	0xef, 0x92, 0x5e, 0xd7, 0xec, 0x14, 0x5c, 0x95, 0x49, 0x0c, 0x69, 0xd1, 0xbe, 0x6d, 0x1a, 0xe1,
	0xa3, 0x59, 0x78, 0x0a, 0xee, 0xa2, 0x94, 0xd2, 0x36, 0x1d, 0xdb, 0x34, 0x02, 0x35, 0xa7, 0x30,
	0x8c, 0x51, 0xcf, 0x95, 0xc8, 0x0b, 0x91, 0xa5, 0xbc, 0x47, 0xed, 0x55, 0x89, 0x3d, 0x84, 0x1e,
	0x26, 0x91, 0x90, 0xbc, 0x4f, 0x3d, 0x5b, 0xb0, 0xc7, 0xe0, 0x16, 0x28, 0x31, 0xbf, 0xcd, 0x52,
	0xe4, 0x07, 0xd4, 0x69, 0x04, 0xe6, 0x41, 0x57, 0x24, 0x7c, 0x40, 0x72, 0x57, 0x24, 0xec, 0x29,
	0x0c, 0x23, 0x89, 0xaa, 0x08, 0x6d, 0x92, 0x4b, 0x0d, 0x20, 0xe9, 0x8a, 0xe2, 0xce, 0x80, 0xad,
	0x18, 0xc2, 0x5c, 0xe1, 0x42, 0xdc, 0x71, 0x20, 0xdf, 0xa4, 0xf1, 0x7d, 0x22, 0x9d, 0x3d, 0x87,
	0xb1, 0x2e, 0x32, 0x85, 0x71, 0xf8, 0x3d, 0x09, 0xbf, 0x95, 0x59, 0x11, 0xf1, 0xe1, 0xb4, 0x33,
	0xeb, 0x05, 0x23, 0x2b, 0x7f, 0x49, 0x3e, 0x1b, 0x91, 0xbd, 0x80, 0xa3, 0x18, 0x73, 0x99, 0xfd,
	0x5c, 0x75, 0x1e, 0x92, 0x73, 0xbc, 0x6c, 0x2c, 0xbd, 0x3e, 0x8c, 0x84, 0x0e, 0xbf, 0xaa, 0xac,
	0xcc, 0x43, 0x73, 0x75, 0x7c, 0x34, 0xed, 0xcc, 0x06, 0xc1, 0x50, 0xe8, 0xf7, 0x46, 0x0b, 0x32,
	0x89, 0x26, 0x4f, 0xe8, 0x30, 0xc6, 0x45, 0x54, 0xca, 0x22, 0x9c, 0x47, 0xf3, 0x5b, 0x8c, 0xb9,
	0x47, 0xbe, 0xb1, 0xd0, 0x97, 0x56, 0xbf, 0x20, 0xd9, 0x1c, 0x59, 0xe8, 0x10, 0xef, 0x0a, 0x54,
	0x69, 0x24, 0xf9, 0x98, 0x5c, 0x20, 0xf4, 0x55, 0xa5, 0xb0, 0x19, 0x4c, 0x84, 0x0e, 0xab, 0x53,
	0xa7, 0xd1, 0x8d, 0xc4, 0x98, 0x4f, 0xc8, 0xe5, 0x09, 0xfd, 0x8e, 0x8e, 0x6c, 0x55, 0xf6, 0x04,
	0xc0, 0x44, 0x55, 0x9e, 0x23, 0xf2, 0xb8, 0x42, 0x57, 0x6d, 0xff, 0x0c, 0x26, 0x0d, 0x3e, 0x01,
	0xea, 0x52, 0x16, 0x8c, 0xc3, 0xc1, 0x9c, 0xb4, 0x98, 0x18, 0x1a, 0x04, 0xcb, 0xd2, 0x7f, 0x06,
	0xde, 0x25, 0x4a, 0xdc, 0x0d, 0x9b, 0xc9, 0x6c, 0x5c, 0x4d, 0x66, 0x4c, 0x5a, 0x9d, 0x59, 0x95,
	0xbe, 0x0f, 0x87, 0x01, 0x46, 0xf1, 0xce, 0xc4, 0x5f, 0x0e, 0x78, 0x4b, 0x53, 0x15, 0xb8, 0x8d,
	0xf2, 0x35, 0x92, 0xbb, 0xbb, 0x48, 0xde, 0xdf, 0x4d, 0xb2, 0xb3, 0x83, 0xe4, 0xde, 0xbd, 0x24,
	0xf7, 0xb7, 0x93, 0x7c, 0x70, 0x1f, 0xc9, 0x83, 0x96, 0x24, 0xbb, 0xed, 0x49, 0x86, 0xd6, 0x24,
	0x0f, 0x5b, 0x92, 0x7c, 0xd8, 0x92, 0xe4, 0x51, 0x2b, 0x92, 0xbd, 0x56, 0x24, 0x8f, 0x5b, 0x90,
	0x3c, 0xd9, 0x20, 0xd9, 0x10, 0x96, 0x2b, 0xd4, 0x98, 0x16, 0x15, 0xe5, 0xcb, 0xd2, 0xbf, 0x00,
	0xef, 0x3a, 0x8f, 0xff, 0xf7, 0x44, 0xae, 0xc7, 0x77, 0xb7, 0x0c, 0x4a, 0x13, 0xd2, 0x40, 0x5d,
	0x92, 0x56, 0x43, 0x5d, 0x95, 0xaf, 0xfe, 0x74, 0xc0, 0x31, 0x46, 0xf6, 0x16, 0xfa, 0x76, 0xbe,
	0xd8, 0xb1, 0x7d, 0xb8, 0xcf, 0xd7, 0x5f, 0xeb, 0x93, 0x47, 0xff, 0xc8, 0x36, 0xdc, 0xdf, 0x33,
	0x6b, 0xed, 0x1c, 0xd5, 0x6b, 0xd7, 0x87, 0xaf, 0x5e, 0xbb, 0x39, 0x6d, 0xfe, 0x1e, 0x7b, 0x03,
	0x8e, 0x19, 0x18, 0xf6, 0xa0, 0xb2, 0xac, 0x8e, 0xd8, 0xc9, 0xf1, 0x86, 0xb8, 0xba, 0xa3, 0x3d,
	0x64, 0xbd, 0xe3, 0xfa, 0xc5, 0xd5, 0x3b, 0x6e, 0x5e, 0x85, 0xbf, 0x77, 0xd3, 0xa7, 0xce, 0xeb,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc6, 0xfa, 0x12, 0xd1, 0xab, 0x06, 0x00, 0x00,
}
