// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/vapp.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateVAppInfo struct {
	Name             string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	CatalogName      string `protobuf:"bytes,2,opt,name=catalog_name,json=catalogName" json:"catalog_name,omitempty"`
	TemplateName     string `protobuf:"bytes,3,opt,name=template_name,json=templateName" json:"template_name,omitempty"`
	Vdc              string `protobuf:"bytes,4,opt,name=vdc" json:"vdc,omitempty"`
	Network          string `protobuf:"bytes,5,opt,name=network" json:"network,omitempty"`
	IpAllocationMode string `protobuf:"bytes,6,opt,name=ip_allocation_mode,json=ipAllocationMode" json:"ip_allocation_mode,omitempty"`
	Memory           string `protobuf:"bytes,7,opt,name=memory" json:"memory,omitempty"`
	Cpu              int32  `protobuf:"varint,8,opt,name=cpu" json:"cpu,omitempty"`
	PowerOn          bool   `protobuf:"varint,9,opt,name=power_on,json=powerOn" json:"power_on,omitempty"`
	StorageProfile   string `protobuf:"bytes,10,opt,name=storage_profile,json=storageProfile" json:"storage_profile,omitempty"`
}

func (m *CreateVAppInfo) Reset()                    { *m = CreateVAppInfo{} }
func (m *CreateVAppInfo) String() string            { return proto1.CompactTextString(m) }
func (*CreateVAppInfo) ProtoMessage()               {}
func (*CreateVAppInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *CreateVAppInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateVAppInfo) GetCatalogName() string {
	if m != nil {
		return m.CatalogName
	}
	return ""
}

func (m *CreateVAppInfo) GetTemplateName() string {
	if m != nil {
		return m.TemplateName
	}
	return ""
}

func (m *CreateVAppInfo) GetVdc() string {
	if m != nil {
		return m.Vdc
	}
	return ""
}

func (m *CreateVAppInfo) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *CreateVAppInfo) GetIpAllocationMode() string {
	if m != nil {
		return m.IpAllocationMode
	}
	return ""
}

func (m *CreateVAppInfo) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func (m *CreateVAppInfo) GetCpu() int32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *CreateVAppInfo) GetPowerOn() bool {
	if m != nil {
		return m.PowerOn
	}
	return false
}

func (m *CreateVAppInfo) GetStorageProfile() string {
	if m != nil {
		return m.StorageProfile
	}
	return ""
}

type CreateVAppResult struct {
	Created    bool            `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	InVappInfo *CreateVAppInfo `protobuf:"bytes,2,opt,name=in_vapp_info,json=inVappInfo" json:"in_vapp_info,omitempty"`
}

func (m *CreateVAppResult) Reset()                    { *m = CreateVAppResult{} }
func (m *CreateVAppResult) String() string            { return proto1.CompactTextString(m) }
func (*CreateVAppResult) ProtoMessage()               {}
func (*CreateVAppResult) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *CreateVAppResult) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *CreateVAppResult) GetInVappInfo() *CreateVAppInfo {
	if m != nil {
		return m.InVappInfo
	}
	return nil
}

type DeleteVAppInfo struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Vdc  string `protobuf:"bytes,2,opt,name=vdc" json:"vdc,omitempty"`
}

func (m *DeleteVAppInfo) Reset()                    { *m = DeleteVAppInfo{} }
func (m *DeleteVAppInfo) String() string            { return proto1.CompactTextString(m) }
func (*DeleteVAppInfo) ProtoMessage()               {}
func (*DeleteVAppInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *DeleteVAppInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeleteVAppInfo) GetVdc() string {
	if m != nil {
		return m.Vdc
	}
	return ""
}

type DeleteVAppResult struct {
	Deleted bool `protobuf:"varint,1,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *DeleteVAppResult) Reset()                    { *m = DeleteVAppResult{} }
func (m *DeleteVAppResult) String() string            { return proto1.CompactTextString(m) }
func (*DeleteVAppResult) ProtoMessage()               {}
func (*DeleteVAppResult) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *DeleteVAppResult) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type ReadVAppInfo struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Vdc  string `protobuf:"bytes,2,opt,name=vdc" json:"vdc,omitempty"`
}

func (m *ReadVAppInfo) Reset()                    { *m = ReadVAppInfo{} }
func (m *ReadVAppInfo) String() string            { return proto1.CompactTextString(m) }
func (*ReadVAppInfo) ProtoMessage()               {}
func (*ReadVAppInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *ReadVAppInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReadVAppInfo) GetVdc() string {
	if m != nil {
		return m.Vdc
	}
	return ""
}

type ReadVAppResult struct {
	Present bool     `protobuf:"varint,1,opt,name=present" json:"present,omitempty"`
	Name    string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Network []string `protobuf:"bytes,3,rep,name=network" json:"network,omitempty"`
}

func (m *ReadVAppResult) Reset()                    { *m = ReadVAppResult{} }
func (m *ReadVAppResult) String() string            { return proto1.CompactTextString(m) }
func (*ReadVAppResult) ProtoMessage()               {}
func (*ReadVAppResult) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ReadVAppResult) GetPresent() bool {
	if m != nil {
		return m.Present
	}
	return false
}

func (m *ReadVAppResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReadVAppResult) GetNetwork() []string {
	if m != nil {
		return m.Network
	}
	return nil
}

func init() {
	proto1.RegisterType((*CreateVAppInfo)(nil), "proto.CreateVAppInfo")
	proto1.RegisterType((*CreateVAppResult)(nil), "proto.CreateVAppResult")
	proto1.RegisterType((*DeleteVAppInfo)(nil), "proto.DeleteVAppInfo")
	proto1.RegisterType((*DeleteVAppResult)(nil), "proto.DeleteVAppResult")
	proto1.RegisterType((*ReadVAppInfo)(nil), "proto.ReadVAppInfo")
	proto1.RegisterType((*ReadVAppResult)(nil), "proto.ReadVAppResult")
}

func init() { proto1.RegisterFile("proto/vapp.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x3d, 0x8f, 0xd3, 0x40,
	0x10, 0x95, 0xed, 0x7c, 0x38, 0x13, 0x63, 0xac, 0x95, 0x40, 0x4b, 0x67, 0x4c, 0x41, 0x8a, 0x28,
	0x48, 0x80, 0xa0, 0x8e, 0xa0, 0xa1, 0x00, 0x4e, 0x2e, 0xa2, 0xeb, 0xac, 0x3d, 0x7b, 0x12, 0x59,
	0x67, 0xef, 0xae, 0x36, 0x9b, 0x44, 0xf7, 0xbf, 0xee, 0x07, 0x9e, 0x3c, 0xfe, 0xca, 0x55, 0xa7,
	0xab, 0xfc, 0xde, 0x9b, 0xb7, 0x33, 0xe3, 0x37, 0x10, 0x69, 0xa3, 0xac, 0xfa, 0x72, 0x16, 0x5a,
	0x6f, 0x08, 0xb2, 0x29, 0x7d, 0x92, 0x47, 0x17, 0xc2, 0x5f, 0x06, 0x85, 0xc5, 0xdd, 0x56, 0xeb,
	0x3f, 0x72, 0xaf, 0x18, 0x83, 0x89, 0x14, 0x35, 0x72, 0x27, 0x76, 0x56, 0x8b, 0x94, 0x30, 0xfb,
	0x08, 0x41, 0x2e, 0xac, 0xa8, 0xd4, 0x21, 0xa3, 0x9a, 0x4b, 0xb5, 0x65, 0xa7, 0xfd, 0x6b, 0x2c,
	0x9f, 0xe0, 0x8d, 0xc5, 0x5a, 0x57, 0xc2, 0x62, 0xeb, 0xf1, 0xc8, 0x13, 0xf4, 0x22, 0x99, 0x22,
	0xf0, 0xce, 0x45, 0xce, 0x27, 0x54, 0x6a, 0x20, 0xe3, 0x30, 0x97, 0x68, 0x2f, 0xca, 0xdc, 0xf3,
	0x29, 0xa9, 0x3d, 0x65, 0x6b, 0x60, 0xa5, 0xce, 0x44, 0x55, 0xa9, 0x5c, 0xd8, 0x52, 0xc9, 0xac,
	0x56, 0x05, 0xf2, 0x19, 0x99, 0xa2, 0x52, 0x6f, 0x87, 0xc2, 0x5f, 0x55, 0x20, 0x7b, 0x0f, 0xb3,
	0x1a, 0x6b, 0x65, 0x1e, 0xf8, 0x9c, 0x1c, 0x1d, 0x6b, 0x26, 0xe6, 0xfa, 0xc4, 0xfd, 0xd8, 0x59,
	0x4d, 0xd3, 0x06, 0xb2, 0x0f, 0xe0, 0x6b, 0x75, 0x41, 0x93, 0x29, 0xc9, 0x17, 0xb1, 0xb3, 0xf2,
	0xd3, 0x39, 0xf1, 0xff, 0x92, 0x7d, 0x86, 0xb7, 0x47, 0xab, 0x8c, 0x38, 0x60, 0xa6, 0x8d, 0xda,
	0x97, 0x15, 0x72, 0xa0, 0x6e, 0x61, 0x27, 0xdf, 0xb4, 0x6a, 0x82, 0x10, 0x8d, 0xa9, 0xa5, 0x78,
	0x3c, 0x55, 0xb6, 0xf9, 0x93, 0x9c, 0xb4, 0x82, 0xa2, 0xf3, 0xd3, 0x9e, 0xb2, 0x9f, 0x10, 0x94,
	0x32, 0x6b, 0xc2, 0xcf, 0x4a, 0xb9, 0x57, 0x94, 0xde, 0xf2, 0xeb, 0xbb, 0xf6, 0x12, 0x9b, 0xe7,
	0xf1, 0xa7, 0x50, 0xca, 0x9d, 0x68, 0x71, 0xf2, 0x03, 0xc2, 0xdf, 0x58, 0xe1, 0x0b, 0xc7, 0xe9,
	0x42, 0x75, 0x87, 0x50, 0x93, 0x35, 0x44, 0xe3, 0xbb, 0x71, 0xbd, 0x82, 0xb4, 0x61, 0xbd, 0x8e,
	0x26, 0xdf, 0x21, 0x48, 0x51, 0x14, 0xaf, 0x9c, 0x71, 0x0b, 0x61, 0xff, 0x6a, 0x9c, 0xa0, 0x0d,
	0x1e, 0x51, 0xda, 0x7e, 0x42, 0x47, 0x87, 0x8e, 0xee, 0x55, 0xc7, 0xab, 0xc3, 0x7b, 0xb1, 0x77,
	0x75, 0xf8, 0xbb, 0x19, 0xe5, 0xf2, 0xed, 0x29, 0x00, 0x00, 0xff, 0xff, 0xa4, 0xb2, 0x01, 0x8d,
	0xb5, 0x02, 0x00, 0x00,
}
