// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/vapp_vm.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateVappVmInfo struct {
	TargetVmName       string `protobuf:"bytes,1,opt,name=target_vm_name,json=targetVmName" json:"target_vm_name,omitempty"`
	TargetVapp         string `protobuf:"bytes,2,opt,name=target_vapp,json=targetVapp" json:"target_vapp,omitempty"`
	TargetVdc          string `protobuf:"bytes,3,opt,name=target_vdc,json=targetVdc" json:"target_vdc,omitempty"`
	SourceVapp         string `protobuf:"bytes,4,opt,name=source_vapp,json=sourceVapp" json:"source_vapp,omitempty"`
	SourceVmName       string `protobuf:"bytes,5,opt,name=source_vm_name,json=sourceVmName" json:"source_vm_name,omitempty"`
	Hostname           string `protobuf:"bytes,6,opt,name=hostname" json:"hostname,omitempty"`
	Password           string `protobuf:"bytes,7,opt,name=password" json:"password,omitempty"`
	PasswordAuto       bool   `protobuf:"varint,8,opt,name=password_auto,json=passwordAuto" json:"password_auto,omitempty"`
	PasswordReset      bool   `protobuf:"varint,9,opt,name=password_reset,json=passwordReset" json:"password_reset,omitempty"`
	CustScript         string `protobuf:"bytes,10,opt,name=cust_script,json=custScript" json:"cust_script,omitempty"`
	Network            string `protobuf:"bytes,11,opt,name=network" json:"network,omitempty"`
	StorageProfile     string `protobuf:"bytes,12,opt,name=storage_profile,json=storageProfile" json:"storage_profile,omitempty"`
	PowerOn            bool   `protobuf:"varint,13,opt,name=power_on,json=powerOn" json:"power_on,omitempty"`
	AllEulasAccepted   bool   `protobuf:"varint,14,opt,name=all_eulas_accepted,json=allEulasAccepted" json:"all_eulas_accepted,omitempty"`
	SourceCatalogName  string `protobuf:"bytes,15,opt,name=source_catalog_name,json=sourceCatalogName" json:"source_catalog_name,omitempty"`
	SourceTemplateName string `protobuf:"bytes,16,opt,name=source_template_name,json=sourceTemplateName" json:"source_template_name,omitempty"`
	IpAllocationMode   string `protobuf:"bytes,17,opt,name=ip_allocation_mode,json=ipAllocationMode" json:"ip_allocation_mode,omitempty"`
}

func (m *CreateVappVmInfo) Reset()                    { *m = CreateVappVmInfo{} }
func (m *CreateVappVmInfo) String() string            { return proto1.CompactTextString(m) }
func (*CreateVappVmInfo) ProtoMessage()               {}
func (*CreateVappVmInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *CreateVappVmInfo) GetTargetVmName() string {
	if m != nil {
		return m.TargetVmName
	}
	return ""
}

func (m *CreateVappVmInfo) GetTargetVapp() string {
	if m != nil {
		return m.TargetVapp
	}
	return ""
}

func (m *CreateVappVmInfo) GetTargetVdc() string {
	if m != nil {
		return m.TargetVdc
	}
	return ""
}

func (m *CreateVappVmInfo) GetSourceVapp() string {
	if m != nil {
		return m.SourceVapp
	}
	return ""
}

func (m *CreateVappVmInfo) GetSourceVmName() string {
	if m != nil {
		return m.SourceVmName
	}
	return ""
}

func (m *CreateVappVmInfo) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *CreateVappVmInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateVappVmInfo) GetPasswordAuto() bool {
	if m != nil {
		return m.PasswordAuto
	}
	return false
}

func (m *CreateVappVmInfo) GetPasswordReset() bool {
	if m != nil {
		return m.PasswordReset
	}
	return false
}

func (m *CreateVappVmInfo) GetCustScript() string {
	if m != nil {
		return m.CustScript
	}
	return ""
}

func (m *CreateVappVmInfo) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *CreateVappVmInfo) GetStorageProfile() string {
	if m != nil {
		return m.StorageProfile
	}
	return ""
}

func (m *CreateVappVmInfo) GetPowerOn() bool {
	if m != nil {
		return m.PowerOn
	}
	return false
}

func (m *CreateVappVmInfo) GetAllEulasAccepted() bool {
	if m != nil {
		return m.AllEulasAccepted
	}
	return false
}

func (m *CreateVappVmInfo) GetSourceCatalogName() string {
	if m != nil {
		return m.SourceCatalogName
	}
	return ""
}

func (m *CreateVappVmInfo) GetSourceTemplateName() string {
	if m != nil {
		return m.SourceTemplateName
	}
	return ""
}

func (m *CreateVappVmInfo) GetIpAllocationMode() string {
	if m != nil {
		return m.IpAllocationMode
	}
	return ""
}

type CreateVappVmResult struct {
	Created bool `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
}

func (m *CreateVappVmResult) Reset()                    { *m = CreateVappVmResult{} }
func (m *CreateVappVmResult) String() string            { return proto1.CompactTextString(m) }
func (*CreateVappVmResult) ProtoMessage()               {}
func (*CreateVappVmResult) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

func (m *CreateVappVmResult) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

type DeleteVappVmInfo struct {
	TargetVmName string `protobuf:"bytes,1,opt,name=target_vm_name,json=targetVmName" json:"target_vm_name,omitempty"`
	TargetVdc    string `protobuf:"bytes,2,opt,name=target_vdc,json=targetVdc" json:"target_vdc,omitempty"`
	TargetVapp   string `protobuf:"bytes,3,opt,name=target_vapp,json=targetVapp" json:"target_vapp,omitempty"`
}

func (m *DeleteVappVmInfo) Reset()                    { *m = DeleteVappVmInfo{} }
func (m *DeleteVappVmInfo) String() string            { return proto1.CompactTextString(m) }
func (*DeleteVappVmInfo) ProtoMessage()               {}
func (*DeleteVappVmInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{2} }

func (m *DeleteVappVmInfo) GetTargetVmName() string {
	if m != nil {
		return m.TargetVmName
	}
	return ""
}

func (m *DeleteVappVmInfo) GetTargetVdc() string {
	if m != nil {
		return m.TargetVdc
	}
	return ""
}

func (m *DeleteVappVmInfo) GetTargetVapp() string {
	if m != nil {
		return m.TargetVapp
	}
	return ""
}

type DeleteVappVmResult struct {
	Deleted bool `protobuf:"varint,1,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *DeleteVappVmResult) Reset()                    { *m = DeleteVappVmResult{} }
func (m *DeleteVappVmResult) String() string            { return proto1.CompactTextString(m) }
func (*DeleteVappVmResult) ProtoMessage()               {}
func (*DeleteVappVmResult) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{3} }

func (m *DeleteVappVmResult) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type ReadVappVmInfo struct {
	TargetVmName string `protobuf:"bytes,1,opt,name=target_vm_name,json=targetVmName" json:"target_vm_name,omitempty"`
	TargetVdc    string `protobuf:"bytes,2,opt,name=target_vdc,json=targetVdc" json:"target_vdc,omitempty"`
	TargetVapp   string `protobuf:"bytes,3,opt,name=target_vapp,json=targetVapp" json:"target_vapp,omitempty"`
}

func (m *ReadVappVmInfo) Reset()                    { *m = ReadVappVmInfo{} }
func (m *ReadVappVmInfo) String() string            { return proto1.CompactTextString(m) }
func (*ReadVappVmInfo) ProtoMessage()               {}
func (*ReadVappVmInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{4} }

func (m *ReadVappVmInfo) GetTargetVmName() string {
	if m != nil {
		return m.TargetVmName
	}
	return ""
}

func (m *ReadVappVmInfo) GetTargetVdc() string {
	if m != nil {
		return m.TargetVdc
	}
	return ""
}

func (m *ReadVappVmInfo) GetTargetVapp() string {
	if m != nil {
		return m.TargetVapp
	}
	return ""
}

type ReadVappVmResult struct {
	TargetVmName     string `protobuf:"bytes,1,opt,name=target_vm_name,json=targetVmName" json:"target_vm_name,omitempty"`
	TargetVapp       string `protobuf:"bytes,2,opt,name=target_vapp,json=targetVapp" json:"target_vapp,omitempty"`
	TargetVdc        string `protobuf:"bytes,3,opt,name=target_vdc,json=targetVdc" json:"target_vdc,omitempty"`
	SourceVapp       string `protobuf:"bytes,4,opt,name=source_vapp,json=sourceVapp" json:"source_vapp,omitempty"`
	SourceVmName     string `protobuf:"bytes,5,opt,name=source_vm_name,json=sourceVmName" json:"source_vm_name,omitempty"`
	Hostname         string `protobuf:"bytes,6,opt,name=hostname" json:"hostname,omitempty"`
	PasswordAuto     bool   `protobuf:"varint,7,opt,name=password_auto,json=passwordAuto" json:"password_auto,omitempty"`
	PasswordReset    bool   `protobuf:"varint,8,opt,name=password_reset,json=passwordReset" json:"password_reset,omitempty"`
	CustScript       string `protobuf:"bytes,9,opt,name=cust_script,json=custScript" json:"cust_script,omitempty"`
	Network          string `protobuf:"bytes,10,opt,name=network" json:"network,omitempty"`
	StorageProfile   string `protobuf:"bytes,11,opt,name=storage_profile,json=storageProfile" json:"storage_profile,omitempty"`
	PowerOn          bool   `protobuf:"varint,12,opt,name=power_on,json=powerOn" json:"power_on,omitempty"`
	AllEulasAccepted bool   `protobuf:"varint,13,opt,name=all_eulas_accepted,json=allEulasAccepted" json:"all_eulas_accepted,omitempty"`
	Present          bool   `protobuf:"varint,14,opt,name=present" json:"present,omitempty"`
	VirtualCpus      int32  `protobuf:"varint,15,opt,name=virtual_cpus,json=virtualCpus" json:"virtual_cpus,omitempty"`
	CoresPerSocket   int32  `protobuf:"varint,16,opt,name=cores_per_socket,json=coresPerSocket" json:"cores_per_socket,omitempty"`
	Memory           int32  `protobuf:"varint,17,opt,name=memory" json:"memory,omitempty"`
}

func (m *ReadVappVmResult) Reset()                    { *m = ReadVappVmResult{} }
func (m *ReadVappVmResult) String() string            { return proto1.CompactTextString(m) }
func (*ReadVappVmResult) ProtoMessage()               {}
func (*ReadVappVmResult) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{5} }

func (m *ReadVappVmResult) GetTargetVmName() string {
	if m != nil {
		return m.TargetVmName
	}
	return ""
}

func (m *ReadVappVmResult) GetTargetVapp() string {
	if m != nil {
		return m.TargetVapp
	}
	return ""
}

func (m *ReadVappVmResult) GetTargetVdc() string {
	if m != nil {
		return m.TargetVdc
	}
	return ""
}

func (m *ReadVappVmResult) GetSourceVapp() string {
	if m != nil {
		return m.SourceVapp
	}
	return ""
}

func (m *ReadVappVmResult) GetSourceVmName() string {
	if m != nil {
		return m.SourceVmName
	}
	return ""
}

func (m *ReadVappVmResult) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *ReadVappVmResult) GetPasswordAuto() bool {
	if m != nil {
		return m.PasswordAuto
	}
	return false
}

func (m *ReadVappVmResult) GetPasswordReset() bool {
	if m != nil {
		return m.PasswordReset
	}
	return false
}

func (m *ReadVappVmResult) GetCustScript() string {
	if m != nil {
		return m.CustScript
	}
	return ""
}

func (m *ReadVappVmResult) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *ReadVappVmResult) GetStorageProfile() string {
	if m != nil {
		return m.StorageProfile
	}
	return ""
}

func (m *ReadVappVmResult) GetPowerOn() bool {
	if m != nil {
		return m.PowerOn
	}
	return false
}

func (m *ReadVappVmResult) GetAllEulasAccepted() bool {
	if m != nil {
		return m.AllEulasAccepted
	}
	return false
}

func (m *ReadVappVmResult) GetPresent() bool {
	if m != nil {
		return m.Present
	}
	return false
}

func (m *ReadVappVmResult) GetVirtualCpus() int32 {
	if m != nil {
		return m.VirtualCpus
	}
	return 0
}

func (m *ReadVappVmResult) GetCoresPerSocket() int32 {
	if m != nil {
		return m.CoresPerSocket
	}
	return 0
}

func (m *ReadVappVmResult) GetMemory() int32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

type UpdateVappVmInfo struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	IsEnabled bool   `protobuf:"varint,2,opt,name=is_enabled,json=isEnabled" json:"is_enabled,omitempty"`
}

func (m *UpdateVappVmInfo) Reset()                    { *m = UpdateVappVmInfo{} }
func (m *UpdateVappVmInfo) String() string            { return proto1.CompactTextString(m) }
func (*UpdateVappVmInfo) ProtoMessage()               {}
func (*UpdateVappVmInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{6} }

func (m *UpdateVappVmInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateVappVmInfo) GetIsEnabled() bool {
	if m != nil {
		return m.IsEnabled
	}
	return false
}

type UpdateVappVmResult struct {
	Updated bool `protobuf:"varint,1,opt,name=updated" json:"updated,omitempty"`
}

func (m *UpdateVappVmResult) Reset()                    { *m = UpdateVappVmResult{} }
func (m *UpdateVappVmResult) String() string            { return proto1.CompactTextString(m) }
func (*UpdateVappVmResult) ProtoMessage()               {}
func (*UpdateVappVmResult) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{7} }

func (m *UpdateVappVmResult) GetUpdated() bool {
	if m != nil {
		return m.Updated
	}
	return false
}

type PowerOnVappVmInfo struct {
	TargetVmName string `protobuf:"bytes,1,opt,name=target_vm_name,json=targetVmName" json:"target_vm_name,omitempty"`
	TargetVdc    string `protobuf:"bytes,2,opt,name=target_vdc,json=targetVdc" json:"target_vdc,omitempty"`
	TargetVapp   string `protobuf:"bytes,3,opt,name=target_vapp,json=targetVapp" json:"target_vapp,omitempty"`
}

func (m *PowerOnVappVmInfo) Reset()                    { *m = PowerOnVappVmInfo{} }
func (m *PowerOnVappVmInfo) String() string            { return proto1.CompactTextString(m) }
func (*PowerOnVappVmInfo) ProtoMessage()               {}
func (*PowerOnVappVmInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{8} }

func (m *PowerOnVappVmInfo) GetTargetVmName() string {
	if m != nil {
		return m.TargetVmName
	}
	return ""
}

func (m *PowerOnVappVmInfo) GetTargetVdc() string {
	if m != nil {
		return m.TargetVdc
	}
	return ""
}

func (m *PowerOnVappVmInfo) GetTargetVapp() string {
	if m != nil {
		return m.TargetVapp
	}
	return ""
}

type PowerOnVappVmResult struct {
	PoweredOn bool `protobuf:"varint,1,opt,name=powered_on,json=poweredOn" json:"powered_on,omitempty"`
}

func (m *PowerOnVappVmResult) Reset()                    { *m = PowerOnVappVmResult{} }
func (m *PowerOnVappVmResult) String() string            { return proto1.CompactTextString(m) }
func (*PowerOnVappVmResult) ProtoMessage()               {}
func (*PowerOnVappVmResult) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{9} }

func (m *PowerOnVappVmResult) GetPoweredOn() bool {
	if m != nil {
		return m.PoweredOn
	}
	return false
}

type PowerOffVappVmInfo struct {
	TargetVmName string `protobuf:"bytes,1,opt,name=target_vm_name,json=targetVmName" json:"target_vm_name,omitempty"`
	TargetVdc    string `protobuf:"bytes,2,opt,name=target_vdc,json=targetVdc" json:"target_vdc,omitempty"`
	TargetVapp   string `protobuf:"bytes,3,opt,name=target_vapp,json=targetVapp" json:"target_vapp,omitempty"`
}

func (m *PowerOffVappVmInfo) Reset()                    { *m = PowerOffVappVmInfo{} }
func (m *PowerOffVappVmInfo) String() string            { return proto1.CompactTextString(m) }
func (*PowerOffVappVmInfo) ProtoMessage()               {}
func (*PowerOffVappVmInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{10} }

func (m *PowerOffVappVmInfo) GetTargetVmName() string {
	if m != nil {
		return m.TargetVmName
	}
	return ""
}

func (m *PowerOffVappVmInfo) GetTargetVdc() string {
	if m != nil {
		return m.TargetVdc
	}
	return ""
}

func (m *PowerOffVappVmInfo) GetTargetVapp() string {
	if m != nil {
		return m.TargetVapp
	}
	return ""
}

type PowerOffVappVmResult struct {
	PoweredOff bool `protobuf:"varint,1,opt,name=powered_off,json=poweredOff" json:"powered_off,omitempty"`
}

func (m *PowerOffVappVmResult) Reset()                    { *m = PowerOffVappVmResult{} }
func (m *PowerOffVappVmResult) String() string            { return proto1.CompactTextString(m) }
func (*PowerOffVappVmResult) ProtoMessage()               {}
func (*PowerOffVappVmResult) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{11} }

func (m *PowerOffVappVmResult) GetPoweredOff() bool {
	if m != nil {
		return m.PoweredOff
	}
	return false
}

type ModifyVappVmMemoryInfo struct {
	TargetVmName string `protobuf:"bytes,1,opt,name=target_vm_name,json=targetVmName" json:"target_vm_name,omitempty"`
	TargetVdc    string `protobuf:"bytes,2,opt,name=target_vdc,json=targetVdc" json:"target_vdc,omitempty"`
	TargetVapp   string `protobuf:"bytes,3,opt,name=target_vapp,json=targetVapp" json:"target_vapp,omitempty"`
	Memory       int32  `protobuf:"varint,4,opt,name=memory" json:"memory,omitempty"`
}

func (m *ModifyVappVmMemoryInfo) Reset()                    { *m = ModifyVappVmMemoryInfo{} }
func (m *ModifyVappVmMemoryInfo) String() string            { return proto1.CompactTextString(m) }
func (*ModifyVappVmMemoryInfo) ProtoMessage()               {}
func (*ModifyVappVmMemoryInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{12} }

func (m *ModifyVappVmMemoryInfo) GetTargetVmName() string {
	if m != nil {
		return m.TargetVmName
	}
	return ""
}

func (m *ModifyVappVmMemoryInfo) GetTargetVdc() string {
	if m != nil {
		return m.TargetVdc
	}
	return ""
}

func (m *ModifyVappVmMemoryInfo) GetTargetVapp() string {
	if m != nil {
		return m.TargetVapp
	}
	return ""
}

func (m *ModifyVappVmMemoryInfo) GetMemory() int32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

type ModifyVappVmMemoryResult struct {
	Modified bool `protobuf:"varint,1,opt,name=modified" json:"modified,omitempty"`
}

func (m *ModifyVappVmMemoryResult) Reset()                    { *m = ModifyVappVmMemoryResult{} }
func (m *ModifyVappVmMemoryResult) String() string            { return proto1.CompactTextString(m) }
func (*ModifyVappVmMemoryResult) ProtoMessage()               {}
func (*ModifyVappVmMemoryResult) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{13} }

func (m *ModifyVappVmMemoryResult) GetModified() bool {
	if m != nil {
		return m.Modified
	}
	return false
}

type ModifyVappVmCPUInfo struct {
	TargetVmName   string `protobuf:"bytes,1,opt,name=target_vm_name,json=targetVmName" json:"target_vm_name,omitempty"`
	TargetVdc      string `protobuf:"bytes,2,opt,name=target_vdc,json=targetVdc" json:"target_vdc,omitempty"`
	TargetVapp     string `protobuf:"bytes,3,opt,name=target_vapp,json=targetVapp" json:"target_vapp,omitempty"`
	VirtualCpus    int32  `protobuf:"varint,4,opt,name=virtual_cpus,json=virtualCpus" json:"virtual_cpus,omitempty"`
	CoresPerSocket int32  `protobuf:"varint,5,opt,name=cores_per_socket,json=coresPerSocket" json:"cores_per_socket,omitempty"`
}

func (m *ModifyVappVmCPUInfo) Reset()                    { *m = ModifyVappVmCPUInfo{} }
func (m *ModifyVappVmCPUInfo) String() string            { return proto1.CompactTextString(m) }
func (*ModifyVappVmCPUInfo) ProtoMessage()               {}
func (*ModifyVappVmCPUInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{14} }

func (m *ModifyVappVmCPUInfo) GetTargetVmName() string {
	if m != nil {
		return m.TargetVmName
	}
	return ""
}

func (m *ModifyVappVmCPUInfo) GetTargetVdc() string {
	if m != nil {
		return m.TargetVdc
	}
	return ""
}

func (m *ModifyVappVmCPUInfo) GetTargetVapp() string {
	if m != nil {
		return m.TargetVapp
	}
	return ""
}

func (m *ModifyVappVmCPUInfo) GetVirtualCpus() int32 {
	if m != nil {
		return m.VirtualCpus
	}
	return 0
}

func (m *ModifyVappVmCPUInfo) GetCoresPerSocket() int32 {
	if m != nil {
		return m.CoresPerSocket
	}
	return 0
}

type ModifyVappVmCPUResult struct {
	Modified bool `protobuf:"varint,1,opt,name=modified" json:"modified,omitempty"`
}

func (m *ModifyVappVmCPUResult) Reset()                    { *m = ModifyVappVmCPUResult{} }
func (m *ModifyVappVmCPUResult) String() string            { return proto1.CompactTextString(m) }
func (*ModifyVappVmCPUResult) ProtoMessage()               {}
func (*ModifyVappVmCPUResult) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{15} }

func (m *ModifyVappVmCPUResult) GetModified() bool {
	if m != nil {
		return m.Modified
	}
	return false
}

func init() {
	proto1.RegisterType((*CreateVappVmInfo)(nil), "proto.CreateVappVmInfo")
	proto1.RegisterType((*CreateVappVmResult)(nil), "proto.CreateVappVmResult")
	proto1.RegisterType((*DeleteVappVmInfo)(nil), "proto.DeleteVappVmInfo")
	proto1.RegisterType((*DeleteVappVmResult)(nil), "proto.DeleteVappVmResult")
	proto1.RegisterType((*ReadVappVmInfo)(nil), "proto.ReadVappVmInfo")
	proto1.RegisterType((*ReadVappVmResult)(nil), "proto.ReadVappVmResult")
	proto1.RegisterType((*UpdateVappVmInfo)(nil), "proto.UpdateVappVmInfo")
	proto1.RegisterType((*UpdateVappVmResult)(nil), "proto.UpdateVappVmResult")
	proto1.RegisterType((*PowerOnVappVmInfo)(nil), "proto.PowerOnVappVmInfo")
	proto1.RegisterType((*PowerOnVappVmResult)(nil), "proto.PowerOnVappVmResult")
	proto1.RegisterType((*PowerOffVappVmInfo)(nil), "proto.PowerOffVappVmInfo")
	proto1.RegisterType((*PowerOffVappVmResult)(nil), "proto.PowerOffVappVmResult")
	proto1.RegisterType((*ModifyVappVmMemoryInfo)(nil), "proto.ModifyVappVmMemoryInfo")
	proto1.RegisterType((*ModifyVappVmMemoryResult)(nil), "proto.ModifyVappVmMemoryResult")
	proto1.RegisterType((*ModifyVappVmCPUInfo)(nil), "proto.ModifyVappVmCPUInfo")
	proto1.RegisterType((*ModifyVappVmCPUResult)(nil), "proto.ModifyVappVmCPUResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for VappVm service

type VappVmClient interface {
	// create a VappVM through vapp
	CreateFromVapp(ctx context.Context, in *CreateVappVmInfo, opts ...grpc.CallOption) (*CreateVappVmResult, error)
	// create a VappVM through catalog
	CreateFromCatalog(ctx context.Context, in *CreateVappVmInfo, opts ...grpc.CallOption) (*CreateVappVmResult, error)
	// create a VappVm
	Create(ctx context.Context, in *CreateVappVmInfo, opts ...grpc.CallOption) (*CreateVappVmResult, error)
	// delete a VappVm
	Delete(ctx context.Context, in *DeleteVappVmInfo, opts ...grpc.CallOption) (*DeleteVappVmResult, error)
	// Read VappVm
	Read(ctx context.Context, in *ReadVappVmInfo, opts ...grpc.CallOption) (*ReadVappVmResult, error)
	// Update VappVm
	Update(ctx context.Context, in *UpdateVappVmInfo, opts ...grpc.CallOption) (*UpdateVappVmResult, error)
	// PowerOn VappVm
	PowerOn(ctx context.Context, in *PowerOnVappVmInfo, opts ...grpc.CallOption) (*PowerOnVappVmResult, error)
	// PowerOff VappVm
	PowerOff(ctx context.Context, in *PowerOffVappVmInfo, opts ...grpc.CallOption) (*PowerOffVappVmResult, error)
	// ModifyCPU VappVm
	ModifyCPU(ctx context.Context, in *ModifyVappVmCPUInfo, opts ...grpc.CallOption) (*ModifyVappVmCPUResult, error)
	// ModifyMemory VappVm
	ModifyMemory(ctx context.Context, in *ModifyVappVmMemoryInfo, opts ...grpc.CallOption) (*ModifyVappVmMemoryResult, error)
}

type vappVmClient struct {
	cc *grpc.ClientConn
}

func NewVappVmClient(cc *grpc.ClientConn) VappVmClient {
	return &vappVmClient{cc}
}

func (c *vappVmClient) CreateFromVapp(ctx context.Context, in *CreateVappVmInfo, opts ...grpc.CallOption) (*CreateVappVmResult, error) {
	out := new(CreateVappVmResult)
	err := grpc.Invoke(ctx, "/proto.VappVm/CreateFromVapp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vappVmClient) CreateFromCatalog(ctx context.Context, in *CreateVappVmInfo, opts ...grpc.CallOption) (*CreateVappVmResult, error) {
	out := new(CreateVappVmResult)
	err := grpc.Invoke(ctx, "/proto.VappVm/CreateFromCatalog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vappVmClient) Create(ctx context.Context, in *CreateVappVmInfo, opts ...grpc.CallOption) (*CreateVappVmResult, error) {
	out := new(CreateVappVmResult)
	err := grpc.Invoke(ctx, "/proto.VappVm/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vappVmClient) Delete(ctx context.Context, in *DeleteVappVmInfo, opts ...grpc.CallOption) (*DeleteVappVmResult, error) {
	out := new(DeleteVappVmResult)
	err := grpc.Invoke(ctx, "/proto.VappVm/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vappVmClient) Read(ctx context.Context, in *ReadVappVmInfo, opts ...grpc.CallOption) (*ReadVappVmResult, error) {
	out := new(ReadVappVmResult)
	err := grpc.Invoke(ctx, "/proto.VappVm/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vappVmClient) Update(ctx context.Context, in *UpdateVappVmInfo, opts ...grpc.CallOption) (*UpdateVappVmResult, error) {
	out := new(UpdateVappVmResult)
	err := grpc.Invoke(ctx, "/proto.VappVm/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vappVmClient) PowerOn(ctx context.Context, in *PowerOnVappVmInfo, opts ...grpc.CallOption) (*PowerOnVappVmResult, error) {
	out := new(PowerOnVappVmResult)
	err := grpc.Invoke(ctx, "/proto.VappVm/PowerOn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vappVmClient) PowerOff(ctx context.Context, in *PowerOffVappVmInfo, opts ...grpc.CallOption) (*PowerOffVappVmResult, error) {
	out := new(PowerOffVappVmResult)
	err := grpc.Invoke(ctx, "/proto.VappVm/PowerOff", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vappVmClient) ModifyCPU(ctx context.Context, in *ModifyVappVmCPUInfo, opts ...grpc.CallOption) (*ModifyVappVmCPUResult, error) {
	out := new(ModifyVappVmCPUResult)
	err := grpc.Invoke(ctx, "/proto.VappVm/ModifyCPU", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vappVmClient) ModifyMemory(ctx context.Context, in *ModifyVappVmMemoryInfo, opts ...grpc.CallOption) (*ModifyVappVmMemoryResult, error) {
	out := new(ModifyVappVmMemoryResult)
	err := grpc.Invoke(ctx, "/proto.VappVm/ModifyMemory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VappVm service

type VappVmServer interface {
	// create a VappVM through vapp
	CreateFromVapp(context.Context, *CreateVappVmInfo) (*CreateVappVmResult, error)
	// create a VappVM through catalog
	CreateFromCatalog(context.Context, *CreateVappVmInfo) (*CreateVappVmResult, error)
	// create a VappVm
	Create(context.Context, *CreateVappVmInfo) (*CreateVappVmResult, error)
	// delete a VappVm
	Delete(context.Context, *DeleteVappVmInfo) (*DeleteVappVmResult, error)
	// Read VappVm
	Read(context.Context, *ReadVappVmInfo) (*ReadVappVmResult, error)
	// Update VappVm
	Update(context.Context, *UpdateVappVmInfo) (*UpdateVappVmResult, error)
	// PowerOn VappVm
	PowerOn(context.Context, *PowerOnVappVmInfo) (*PowerOnVappVmResult, error)
	// PowerOff VappVm
	PowerOff(context.Context, *PowerOffVappVmInfo) (*PowerOffVappVmResult, error)
	// ModifyCPU VappVm
	ModifyCPU(context.Context, *ModifyVappVmCPUInfo) (*ModifyVappVmCPUResult, error)
	// ModifyMemory VappVm
	ModifyMemory(context.Context, *ModifyVappVmMemoryInfo) (*ModifyVappVmMemoryResult, error)
}

func RegisterVappVmServer(s *grpc.Server, srv VappVmServer) {
	s.RegisterService(&_VappVm_serviceDesc, srv)
}

func _VappVm_CreateFromVapp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVappVmInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VappVmServer).CreateFromVapp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VappVm/CreateFromVapp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VappVmServer).CreateFromVapp(ctx, req.(*CreateVappVmInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _VappVm_CreateFromCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVappVmInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VappVmServer).CreateFromCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VappVm/CreateFromCatalog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VappVmServer).CreateFromCatalog(ctx, req.(*CreateVappVmInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _VappVm_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVappVmInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VappVmServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VappVm/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VappVmServer).Create(ctx, req.(*CreateVappVmInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _VappVm_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVappVmInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VappVmServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VappVm/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VappVmServer).Delete(ctx, req.(*DeleteVappVmInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _VappVm_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadVappVmInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VappVmServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VappVm/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VappVmServer).Read(ctx, req.(*ReadVappVmInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _VappVm_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVappVmInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VappVmServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VappVm/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VappVmServer).Update(ctx, req.(*UpdateVappVmInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _VappVm_PowerOn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PowerOnVappVmInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VappVmServer).PowerOn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VappVm/PowerOn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VappVmServer).PowerOn(ctx, req.(*PowerOnVappVmInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _VappVm_PowerOff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PowerOffVappVmInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VappVmServer).PowerOff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VappVm/PowerOff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VappVmServer).PowerOff(ctx, req.(*PowerOffVappVmInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _VappVm_ModifyCPU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyVappVmCPUInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VappVmServer).ModifyCPU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VappVm/ModifyCPU",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VappVmServer).ModifyCPU(ctx, req.(*ModifyVappVmCPUInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _VappVm_ModifyMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyVappVmMemoryInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VappVmServer).ModifyMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VappVm/ModifyMemory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VappVmServer).ModifyMemory(ctx, req.(*ModifyVappVmMemoryInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _VappVm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.VappVm",
	HandlerType: (*VappVmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFromVapp",
			Handler:    _VappVm_CreateFromVapp_Handler,
		},
		{
			MethodName: "CreateFromCatalog",
			Handler:    _VappVm_CreateFromCatalog_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _VappVm_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _VappVm_Delete_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _VappVm_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _VappVm_Update_Handler,
		},
		{
			MethodName: "PowerOn",
			Handler:    _VappVm_PowerOn_Handler,
		},
		{
			MethodName: "PowerOff",
			Handler:    _VappVm_PowerOff_Handler,
		},
		{
			MethodName: "ModifyCPU",
			Handler:    _VappVm_ModifyCPU_Handler,
		},
		{
			MethodName: "ModifyMemory",
			Handler:    _VappVm_ModifyMemory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/vapp_vm.proto",
}

func init() { proto1.RegisterFile("proto/vapp_vm.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 933 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0xb6, 0x12, 0xfd, 0x50, 0x23, 0x59, 0x91, 0xd7, 0xf9, 0xa1, 0xd9, 0x1a, 0x4e, 0xd9, 0x14,
	0xf5, 0x21, 0x70, 0x8b, 0xa6, 0x68, 0x7b, 0x2a, 0x60, 0x28, 0x4e, 0x91, 0x83, 0x6b, 0x81, 0xa9,
	0x7d, 0x25, 0x36, 0xe4, 0xd2, 0x25, 0x42, 0x72, 0x17, 0xcb, 0xa5, 0x5c, 0xf7, 0xd4, 0xa7, 0xe8,
	0xbb, 0xf4, 0x0d, 0x7a, 0xef, 0x0b, 0x15, 0x9c, 0x5d, 0x52, 0xd4, 0x4f, 0x6a, 0xc1, 0x07, 0x1d,
	0x7a, 0x92, 0xe6, 0xfb, 0x66, 0x76, 0xbe, 0x25, 0xe7, 0xdb, 0x25, 0xec, 0x0b, 0xc9, 0x15, 0xff,
	0x6a, 0x46, 0x85, 0xf0, 0x67, 0xe9, 0x09, 0x46, 0xa4, 0x83, 0x3f, 0xee, 0x1f, 0x1d, 0x18, 0x4f,
	0x24, 0xa3, 0x8a, 0x5d, 0x51, 0x21, 0xae, 0xd2, 0xb7, 0x59, 0xc4, 0xc9, 0x0b, 0x18, 0x29, 0x2a,
	0xaf, 0x99, 0xf2, 0x67, 0xa9, 0x9f, 0xd1, 0x94, 0xd9, 0xad, 0xe7, 0xad, 0xe3, 0xbe, 0x37, 0xd4,
	0xe8, 0x55, 0xfa, 0x33, 0x4d, 0x19, 0x39, 0x82, 0x41, 0x95, 0x45, 0x85, 0xb0, 0x1f, 0x60, 0x0a,
	0x98, 0x14, 0x2a, 0x04, 0x39, 0x04, 0xa8, 0x12, 0xc2, 0xc0, 0x7e, 0x88, 0x7c, 0xdf, 0xf0, 0x61,
	0x50, 0xd6, 0xe7, 0xbc, 0x90, 0x01, 0xd3, 0xf5, 0x6d, 0x5d, 0xaf, 0x21, 0xac, 0x7f, 0x01, 0xa3,
	0x2a, 0xc1, 0xc8, 0xe8, 0x68, 0x19, 0x26, 0x47, 0xcb, 0x70, 0xc0, 0xfa, 0x95, 0xe7, 0x0a, 0xf9,
	0x2e, 0xf2, 0x75, 0x5c, 0x72, 0x82, 0xe6, 0xf9, 0x0d, 0x97, 0xa1, 0xdd, 0xd3, 0x5c, 0x15, 0x93,
	0xcf, 0x61, 0xb7, 0xfa, 0xef, 0xd3, 0x42, 0x71, 0xdb, 0x7a, 0xde, 0x3a, 0xb6, 0xbc, 0x61, 0x05,
	0x9e, 0x16, 0x8a, 0x93, 0x2f, 0x60, 0x54, 0x27, 0x49, 0x96, 0x33, 0x65, 0xf7, 0x31, 0xab, 0x2e,
	0xf5, 0x4a, 0xb0, 0xdc, 0x4a, 0x50, 0xe4, 0xca, 0xcf, 0x03, 0x19, 0x0b, 0x65, 0x83, 0xde, 0x4a,
	0x09, 0xbd, 0x43, 0x84, 0xd8, 0xd0, 0xcb, 0x98, 0xba, 0xe1, 0xf2, 0x83, 0x3d, 0x40, 0xb2, 0x0a,
	0xc9, 0x97, 0xf0, 0x28, 0x57, 0x5c, 0xd2, 0x6b, 0xe6, 0x0b, 0xc9, 0xa3, 0x38, 0x61, 0xf6, 0x10,
	0x33, 0x46, 0x06, 0x9e, 0x6a, 0x94, 0x1c, 0x80, 0x25, 0xf8, 0x0d, 0x93, 0x3e, 0xcf, 0xec, 0x5d,
	0x14, 0xd1, 0xc3, 0xf8, 0x22, 0x23, 0x2f, 0x81, 0xd0, 0x24, 0xf1, 0x59, 0x91, 0xd0, 0xdc, 0xa7,
	0x41, 0xc0, 0x84, 0x62, 0xa1, 0x3d, 0xc2, 0xa4, 0x31, 0x4d, 0x92, 0xb3, 0x92, 0x38, 0x35, 0x38,
	0x39, 0x81, 0x7d, 0xf3, 0x58, 0x03, 0xaa, 0x68, 0xc2, 0xaf, 0xf5, 0xb3, 0x7d, 0x84, 0x5d, 0xf7,
	0x34, 0x35, 0xd1, 0x0c, 0x3e, 0xe0, 0xaf, 0xe1, 0xb1, 0xc9, 0x57, 0x2c, 0x15, 0x09, 0x55, 0x4c,
	0x17, 0x8c, 0xb1, 0x80, 0x68, 0xee, 0x17, 0x43, 0x61, 0xc5, 0x4b, 0x20, 0xb1, 0xf0, 0x69, 0x92,
	0xf0, 0x80, 0xaa, 0x98, 0x67, 0x7e, 0xca, 0x43, 0x66, 0xef, 0x61, 0xfe, 0x38, 0x16, 0xa7, 0x35,
	0x71, 0xce, 0x43, 0xe6, 0x9e, 0x00, 0x69, 0x4e, 0xa0, 0xc7, 0xf2, 0x22, 0xc1, 0x27, 0x16, 0x20,
	0x1a, 0xe2, 0xf0, 0x59, 0x5e, 0x15, 0xba, 0xbf, 0xc1, 0xf8, 0x35, 0x4b, 0xd8, 0x3d, 0x26, 0x76,
	0x71, 0x20, 0x1f, 0xac, 0x19, 0xc8, 0xe6, 0x40, 0x3f, 0x5c, 0x1e, 0xe8, 0x52, 0x69, 0xb3, 0xf3,
	0x5c, 0x69, 0x88, 0x68, 0xad, 0xd4, 0x84, 0xee, 0x0c, 0x46, 0x1e, 0xa3, 0xe1, 0xd6, 0x75, 0xfe,
	0xd3, 0x86, 0xf1, 0xbc, 0xb1, 0x91, 0xf9, 0xbf, 0x31, 0xf5, 0x8a, 0x71, 0x7b, 0x1b, 0x19, 0xd7,
	0xda, 0xc0, 0xb8, 0xfd, 0xff, 0x32, 0x2e, 0xdc, 0x69, 0xdc, 0xc1, 0x9d, 0xc6, 0x1d, 0x6e, 0x62,
	0xdc, 0xdd, 0x8f, 0x18, 0xd7, 0x86, 0x9e, 0x28, 0xf7, 0x92, 0x29, 0xe3, 0xed, 0x2a, 0x24, 0x9f,
	0xc1, 0x70, 0x16, 0x4b, 0x55, 0xd0, 0xc4, 0x0f, 0x44, 0x91, 0xa3, 0x97, 0x3b, 0xde, 0xc0, 0x60,
	0x13, 0x51, 0xe4, 0xe4, 0x18, 0xc6, 0x01, 0x97, 0x2c, 0xf7, 0x05, 0x93, 0x7e, 0xce, 0x83, 0x0f,
	0x4c, 0xa1, 0x83, 0x3b, 0xde, 0x08, 0xf1, 0x29, 0x93, 0xef, 0x10, 0x25, 0x4f, 0xa1, 0x9b, 0xb2,
	0x94, 0xcb, 0x5b, 0x74, 0x6c, 0xc7, 0x33, 0x91, 0x7b, 0x06, 0xe3, 0x4b, 0x11, 0x2e, 0xde, 0x14,
	0x04, 0xda, 0x8d, 0x51, 0xc2, 0xff, 0xe5, 0x84, 0xc4, 0xb9, 0xcf, 0x32, 0xfa, 0x3e, 0x61, 0x21,
	0x4e, 0x90, 0xe5, 0xf5, 0xe3, 0xfc, 0x4c, 0x03, 0xa5, 0x89, 0x9a, 0xcb, 0xcc, 0x4d, 0x54, 0x20,
	0x5a, 0x9b, 0xc8, 0x84, 0xee, 0x2d, 0xec, 0x4d, 0xf5, 0xe3, 0xda, 0xba, 0x8f, 0xbe, 0x85, 0xfd,
	0x85, 0xd6, 0x46, 0xeb, 0x21, 0x00, 0xbe, 0x40, 0x16, 0x96, 0xaf, 0x54, 0xcb, 0xed, 0x1b, 0xe4,
	0x22, 0x73, 0x7f, 0x07, 0xa2, 0xab, 0xa2, 0x68, 0xeb, 0x8a, 0xbf, 0x87, 0xc7, 0x8b, 0xbd, 0x8d,
	0xe4, 0x23, 0x18, 0xd4, 0x92, 0xa3, 0xc8, 0x68, 0xae, 0x76, 0x71, 0x11, 0x45, 0xee, 0x9f, 0x2d,
	0x78, 0x7a, 0xce, 0xc3, 0x38, 0xba, 0xd5, 0x75, 0xe7, 0xf8, 0xce, 0xb7, 0xa7, 0xbc, 0x31, 0x75,
	0xed, 0x85, 0xa9, 0xfb, 0x0e, 0xec, 0x55, 0x5d, 0x66, 0x57, 0x0e, 0x58, 0x69, 0xc9, 0xc5, 0xf5,
	0xd4, 0xd4, 0xb1, 0xfb, 0x77, 0x0b, 0xf6, 0x9b, 0x85, 0x93, 0xe9, 0xe5, 0x16, 0x77, 0xb3, 0x6c,
	0xc8, 0xf6, 0x66, 0x86, 0xec, 0xac, 0x33, 0xa4, 0xfb, 0x0a, 0x9e, 0x2c, 0xed, 0xe4, 0xee, 0xfd,
	0x7f, 0xf3, 0x57, 0x07, 0xba, 0x3a, 0x9f, 0xbc, 0x81, 0x91, 0xbe, 0x60, 0xdf, 0x48, 0x9e, 0xa2,
	0xbc, 0x67, 0xfa, 0x23, 0xf0, 0x64, 0xf9, 0xcb, 0xcf, 0x39, 0x58, 0x43, 0xe8, 0x66, 0xee, 0x0e,
	0x79, 0x0b, 0x7b, 0xf3, 0x75, 0xcc, 0x17, 0xc2, 0x3d, 0x97, 0xfa, 0x11, 0xba, 0x1a, 0xbf, 0x7f,
	0xbd, 0xbe, 0x89, 0xeb, 0xfa, 0xe5, 0x4f, 0x82, 0xba, 0x7e, 0xf5, 0xc6, 0x76, 0x77, 0xc8, 0x0f,
	0xd0, 0x2e, 0x2f, 0x48, 0xf2, 0xc4, 0x24, 0x2d, 0x5e, 0xd3, 0xce, 0xb3, 0x15, 0xb8, 0xd9, 0x59,
	0x1f, 0x5f, 0x75, 0xe7, 0xe5, 0x43, 0xb1, 0xee, 0xbc, 0x7a, 0xcc, 0xb9, 0x3b, 0xe4, 0x14, 0x7a,
	0xe6, 0x4c, 0x21, 0xb6, 0xc9, 0x5b, 0x39, 0xde, 0x1c, 0x67, 0x1d, 0x53, 0x2f, 0xf1, 0x1a, 0xac,
	0xca, 0xe4, 0xe4, 0x60, 0x21, 0xb3, 0x79, 0xe2, 0x38, 0x9f, 0xac, 0xa5, 0xea, 0x55, 0x7e, 0x82,
	0xbe, 0x9e, 0xaa, 0xc9, 0xf4, 0x92, 0x54, 0x0d, 0xd7, 0x38, 0xc6, 0xf9, 0x74, 0x3d, 0x57, 0x2f,
	0x34, 0x85, 0xa1, 0xa6, 0xb4, 0x37, 0xc9, 0xe1, 0x9a, 0xfc, 0xf9, 0x71, 0xe2, 0x1c, 0x7d, 0x94,
	0xae, 0x56, 0x7c, 0xdf, 0xc5, 0x8c, 0x57, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x57, 0xdf, 0x46,
	0xf7, 0xb9, 0x0c, 0x00, 0x00,
}
